### ISSUE TITLE
Accounting for Perspective distortion

### ISSUE THREAD

**Issue by Abhijit-2592** [DIPlib/diplib#10]
In the below image I am trying to measure the diameter of the 4 small holes.
![image_01](https://user-images.githubusercontent.com/29851832/38535707-7311e2b6-3ca2-11e8-8766-ce35642870f7.png)

```
import numpy as np
import PyDIP as dip
import pandas as pd
import cv2

"""
I am using 3 appraches to measure the Diameter of the holes

1) Using Mean radius returned by 'Radius'
2) Mean of the axes returned by 'Dimensional Ellipsoid' 
3) Using Area 'Size' to calculate the Diameter

"""

dip_img = dip.Image(cv2.imread("./hub_693/image_01.png",0))
OD = ~dip.Threshold(dip.Gauss(dip_img))[0]
OD = dip.EdgeObjectsRemove(OD)
OD = dip.Opening(dip.Closing(OD,9),9)
ID = dip.EdgeObjectsRemove(~OD)
#label the images
lab_OD = dip.Label(OD,minSize = 10000)
lab_ID = dip.Label(ID,minSize = 1000,maxSize=30000)
# a placeholder dataframe to hold the result
df = pd.DataFrame(columns=['feature','maxD','meanD','minD','center','axis_x','axis_y','mean_axis','size','dia_measured_from_size'])
#Measurement
msr_OD =  dip.MeasurementTool.Measure(lab_OD,dip_img,['Radius','Center','Inertia','DimensionsEllipsoid','Size'])
msr_ID =  dip.MeasurementTool.Measure(lab_ID,dip_img,['Radius','Center','Inertia','DimensionsEllipsoid','Size'])
# add OD values
df.loc[0] = 'OD',msr_OD[1]['Radius'][0]*2,msr_OD[1]['Radius'][1]*2,msr_OD[1]['Radius'][2]*2,tuple(msr_OD[1]['Center']),msr_OD[1]['DimensionsEllipsoid'][0],msr_OD[1]['DimensionsEllipsoid'][1],(msr_OD[1]['DimensionsEllipsoid'][0] + msr_OD[1]['DimensionsEllipsoid'][1])/2,msr_OD[1]['Size'][0],2*np.sqrt(msr_OD[1]['Size'][0] / np.pi)
# add values for 4 PCD holes
object_ids = msr_ID.Objects()
for i in object_ids:
    df.loc[i] = 'hole_{}'.format(i),msr_ID[i]['Radius'][0]*2,msr_ID[i]['Radius'][1]*2,msr_ID[i]['Radius'][2]*2,tuple(msr_ID[i]['Center']),msr_ID[i]['DimensionsEllipsoid'][0],msr_ID[i]['DimensionsEllipsoid'][1],(msr_ID[i]['DimensionsEllipsoid'][0]+msr_ID[i]['DimensionsEllipsoid'][1])/2,msr_ID[i]['Size'][0],2*np.sqrt(msr_ID[i]['Size'][0] / np.pi)
```
I have pasted the Output of the above dataframe. (I have also added the real mm value of the measured features, except the last column all the other dimensions are in Pixels)

![screenshot from 2018-04-10 09-53-46](https://user-images.githubusercontent.com/29851832/38536163-54aa3c44-3ca5-11e8-96c8-26dd25393482.png)

As you can see from the above dataframe, For the same physical size of the holes, I am getting 2 different pixel values (around 0.7 to 1 pixel error). This is because, the circle is seen as an ellipse because of perspective distortion. How can I correct it? I tried a naive approach by calibrating the camera and doing a birds eye projection. Still it doesn't seem to work. Any suggestions? Thanks

Upon Reading I found that people use Telecentric lenses to remove perspective errors. Any way to approximate the Telecentric lenses property using this library or camera calibration in general?

**Comment by crisluengo** [comment]
I don't think this is the right venue for this type of question. Let's leave the Issues for bugs/feature requests/comments on the software.

That said, I don't think you can easily work around this problem, as you will always see the sides of the object unless all light travels exactly parallel to the optical axis and the vertical axis of the object. This is not possible with any normal camera. One approach could be to make the sides of the object more reflective (they do reflect some light, I can see the sides being lighter than the top surface that is not illuminated). The more light they appear in the image, the easier it will be to distinguish the top surface of the object from everything else. Next, you need to adjust your segmentation to extract only the top surface, by reducing the threshold value you use.
