### ISSUE TITLE
Implementing DIPimage tests from DIPlib 2

### ISSUE THREAD

**Issue by ronligt** [DIPlib/diplib#100]
I've found the version 2 DIPimage tests. I can put these tests in `dipimage/tests/archive`. We can check later if and how we can reuse these tests. Okay?

**Comment by crisluengo** [comment]
Sounds good to me!

**Comment by ronligt** [comment]
Files have been added.

**Comment by crisluengo** [comment]
@ronligt Congratulations on issue number 100!!!

**Comment by crisluengo** [comment]
5f4346d1b0c7a71171432ee4b8fe8805a6a544ce

**Comment by crisluengo** [comment]
This is far from a complete test suite, but it will verify that the toolbox in general runs, and will test a few basic stuff thoroughly. But the second half of `filtering.m` just runs a bunch of filter functions, it doesn't verify their outputs in any way.

The most important thing to add here, at some point, is tests for the MATLAB code in DIPimage, and tests for the glue between MATLAB and DIPlib. Whether the filters produce the right results is something that should be tested in the DIPlib test suite (which also still has lots of gaps).
