### ISSUE TITLE
pip install diplib not working

### ISSUE THREAD

**Issue by shrinand1996** [DIPlib/diplib#108]
**Component**
Select one or more of: DIPlib / DIPimage / PyDIP / Documentation / CMake build scripts.
Include the release version (if installed from a binary distribution) or the Git commit ID (if installed from sources).

**Describe the bug**
A clear and concise description of what the bug is. Include a description of observed results and expected results.

**To Reproduce**
If applicable, include complete, runnable code to reproduce the behavior.

**System information:**
 - What OS do you have? [e.g. Ubuntu 16, Windows 10]
 - If PyDIP, what version of Python do you have?
 - If DIPimage, what version of MATLAB do you have? (type `ver` at the MATLAB command prompt, and copy-paste the result here).
 - If compiled from sources, what compiler and version did you use?

**Comment by crisluengo** [comment]
Please edit the issue to describe the problem, what you did, and what you observed. The text in the template is meant to guide you through the process.
