### ISSUE TITLE
Import diplib ---> Restarting kernel... in Spyder on Python v3.9.7

### ISSUE THREAD

**Issue by copy-paste-master** [DIPlib/diplib#114]
I am using Python version 3.9.7 on Spyder IDE on macOS, after I pip install diplib, then when I try import diplib as dip, it immediately freezes and goes to 'restarting kernel'...which is what I describe as crashing. Has anyone tried running this on Spyder recently? First time trying this library.

**Comment by crisluengo** [comment]
I have never used Spyder.

Try opening a Python session in your shell (Command-space, then type "Terminal"). In this session, `import diplib as dip`, and see what happens. Maybe there is some error message that is shown here but not in your IDE.

Also, let us know: what version of macOS do you have, and do you have an Intel or an Apple M1 chip?

**Comment by wcaarls** [comment]
This does not seem to occur on Linux (Spyder from current Anaconda / Python 3.9.12)

**Comment by copy-paste-master** [comment]
I have m1 Mac OS. I checked I don’t have this problem with windows.
I only wanted to use the radial averaging and was able to do so on my windows comp, but something is wrong I must probably do it myself from scratch bc I don’t understand exactly what the radial average is doing. Anyway thanks for your help.

**Comment by crisluengo** [comment]
@copy-paste-master I have two M1 macs, and never had any issues with DIPlib. It would be great if you could help us pin-point the issue.

The first thing to do would be to determine if this is a Spyder issue or an Anaconda issue. If you start up a Python session outside of Spyder, as I described above, and import diplib, do things work correctly, or do you get a crash and/or error message?

Thanks!
