### ISSUE TITLE
how to cite this library?

### ISSUE THREAD

**Issue by Abhijit-2592** [DIPlib/diplib#12]
I am using this library for my research. Is there any preferred way to cite this library?

**Comment by crisluengo** [comment]
Thanks for the question!

With previous versions, just about all of our users used the MATLAB interface exclusively (DIPimage). We never expected citations, but quite a few people have cited its user manual. But that is probably not the right reference if you're using the new C++ library or its Python interface.

We should write a paper about the new library infrastructure, so we have something that can be referenced.

In the mean time, I guess you'll just have to reference the GitHub link.

**Comment by Abhijit-2592** [comment]
Thanks I will cite the link then.

**Comment by manishspm09** [comment]
I am getting following error with give code.

Code:
import PyDIP as dip
import math

# Load image and set pixel size
img = dip.ImageReadTIFF('/home/cris/tmp/machined_piece.tif')
img.SetPixelSize(dip.PixelSize(0.042 * dip.Units("mm")))

Error:
module 'PyDIP' has no attribute 'ImageReadTIFF'

**Comment by crisluengo** [comment]
@manishspm09 Could you please start a new issue for this? Include in your issue whether you can call other PyDIP functions (for example try `dip.Gauss`, don't worry about putting in the right arguments, it's just to see if the function exists or not). Also share your version of Python, operating system, etc.

**Comment by manishspm09** [comment]
Sure. Have started new issue with all detail
