### ISSUE TITLE
pydip built from source fails to import

### ISSUE THREAD

**Issue by anntzer** [DIPlib/diplib#126]
**Component**
pydip

**Describe the bug**
Building pydip from source results in a library that fails to import

**To Reproduce**
```
$ mkdir build && cd build && cmake .. && make && make pip_install && python -c 'import diplib'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/some/prefix/lib/python3.10/site-packages/diplib/__init__.py", line 52, in <module>
    from .PyDIP_bin import *
ImportError: dynamic module does not define module export function (PyInit_PyDIP_bin)
```
Dumping the exported symbols from PyDIP_bin (`nm -gD PyDIP_bin.cpython-310-x86_64-linux-gnu.so`) shows that that symbol is indeed absent.

**System information:**
 - What OS do you have? fedora37
 - If PyDIP, what version of Python do you have? python 3.10 from conda-forge; the entire compiler toolchain is from conda-forge too.
 - If DIPimage, what version of MATLAB do you have? (type `ver` at the MATLAB command prompt, and copy-paste the result here).
 - If compiled from sources, what compiler and version did you use? g++ (conda-forge gcc 12.2.0-19) 12.2.0

**Comment by anntzer** [comment]
I tried with `cmake -DDIP_PYDIP_WHEEL_INCLUDE_LIBS=On ..` and things fail with the same error.  Haven't tried with make install as I'd rather not move stuff into /usr; is it possible to install into a prefix?
Note, though, that the error ("ImportError: dynamic module does not define module export function (PyInit_PyDIP_bin)") suggests that the problem is not with finding diplib(?)

**Comment by crisluengo** [comment]
Yes, you can install into any prefix.

My working hypothesis is that the error message is inaccurate, that it cannot load the PyInit_PyDIP_bin module because some of its dependencies are missing.

It not working with the libraries included in the wheel is strange though. That might indicate some other issue. Check the Python version in thr CMake configuration output, and make sure it’s identical to the version of Python you’re trying to run this in. If not, configure in the CMake call the Python executable.

**Comment by anntzer** [comment]
CMakeCache.txt says e.g. that
```
//Path to a program.
PYTHON_EXECUTABLE:FILEPATH=/home/antony/miniconda3/envs/default/bin/python

//Path to a library.
PYTHON_LIBRARY:FILEPATH=/home/antony/miniconda3/envs/default/lib/libpython3.10.so
```
which is correct.

I'll continue investigating...

**Comment by crisluengo** [comment]
Closing this because it's been inactive for long. Please reopen if you ever learn more!
