### ISSUE TITLE
Matlab R2018b

### ISSUE THREAD

**Issue by wcaarls** [DIPlib/diplib#13]
I'm having trouble running dipimage in Matlab R2018b under Linux. The error is:

Invalid MEX-file '/usr/local/share/DIPimage/private/numberofthreads.mexa64': Gateway function is missing.

It turns out that mexFunction in mex.h is not declared with the right visibility by default:

```c
#ifdef _MSC_VER
# define MWMEX_EXPORT_SYM __declspec(dllexport)
#elif __GNUC__ >= 4
# define MWMEX_EXPORT_SYM __attribute__ ((visibility("default")))
#else
# define MWMEX_EXPORT_SYM
#endif

#ifdef MW_NEEDS_VERSION_H
# define MEXFUNCTION_LINKAGE LIBMWMEX_API_EXTERN_C MWMEX_EXPORT_SYM
#else
# define MEXFUNCTION_LINKAGE LIBMWMEX_API_EXTERN_C
#endif
```

Only when `MW_NEEDS_VERSION_H` is defined, the visibility is correct. Defining that before including mex.h solves the problem, but does not seem the correct way of doing things...

**Comment by crisluengo** [comment]
It seems like they changed something since R2018a, because I got it to work there.

I'll look into this tonight. Maybe `MW_NEEDS_VERSION_H` is a macro that is defined by the `mex` command, and we should be replicating that.

**Comment by crisluengo** [comment]
For MATLAB R2018a This bit reads as follows:

```
#ifdef _WIN32
#       define DLL_EXPORT_SYM __declspec(dllexport)
#       define SUPPORTS_PRAGMA_ONCE
#elif __GNUC__ >= 4
#       define DLL_EXPORT_SYM __attribute__ ((visibility("default")))
#       define SUPPORTS_PRAGMA_ONCE
#else
#       define DLL_EXPORT_SYM
#endif

#ifdef DLL_EXPORT_SYM
# define MEXFUNCTION_LINKAGE EXTERN_C DLL_EXPORT_SYM
#else
# ifdef MW_NEEDS_VERSION_H
#  include "version.h"
#  define MEXFUNCTION_LINKAGE EXTERN_C DLL_EXPORT_SYM
# else
#  define MEXFUNCTION_LINKAGE EXTERN_C
# endif
#endif
```

**Comment by crisluengo** [comment]
Please try this: https://github.com/DIPlib/diplib/commit/ea8cb77d1b3e794037462911e5a037739d1a1778

I have been working on the `FindMatlab.cmake` script over here: https://gitlab.kitware.com/cmake/cmake/merge_requests/2442 (quite the coincidence that you bring this up at the same time). I've copied that improved script into the `tools/` directory of our repository and am using that one instead of the default one. It works correctly on my Mac with both GCC and Clang, and for both R2017a and R2018a. But I could already compile correctly for those, so no big change there.

But there is new stuff in it for exporting the requited function names, it no longer relies on properly defined macros to determine what needs to be exported.

Could you please test it to see if this solves your issue?

If you use Linux (as I assume you do), could you please also comment the CMake PR? I'm sure they'll like to know if the changes work on Linux.

**Comment by wcaarls** [comment]
This does not solve the issue. Apparently, `-fvisibility=hidden` overwrites the linker script. From a small test:

```
$ cat source.c
void global_sym(void) { }
void local_sym(void) { }
$ cat version.map
{ global: global_sym; local: local_sym; };
$ gcc -o source.o -fvisibility=hidden -c source.c
$ gcc -shared -o source.so source.o -Wl,--version-script=version.map && nm source.so | grep sym
000000000000055a t global_sym
0000000000000561 t local_sym
$ gcc -o source.o -c source.c
$ gcc -shared -o source.so source.o -Wl,--version-script=version.map && nm source.so | grep sym
000000000000057a T global_sym
0000000000000581 t local_sym
```

`global_sym` is only actually exported in the second case (it also only appears in `nm -D` there)

**Comment by crisluengo** [comment]
The trick is to remove the `-fvisibility` flag while compiling MEX files, then. https://stackoverflow.com/questions/8129782/version-script-and-hidden-visibility

BTW: I'm just now patching up this commit, there was still an issue there. I hadn't noticed because of cached variables in CMake.

**Comment by crisluengo** [comment]
Could you try to see if adding

    set_target_properties(MEX_${target} PROPERTIES COMPILE_FLAGS "-fvisibility=default")

to the file `dipimage/CMakeLists.txt` just after the `matlab_add_mex` call fixes this?

**Comment by wcaarls** [comment]
I suspect that should do the trick. Will test this when I get back to work on Monday. I don't have Matlab R2018b at home, and can't reach my work computer at the moment.

**Comment by wcaarls** [comment]
It works (at least under Linux). Thanks!

**Comment by crisluengo** [comment]
Could you please try this version? 6789920962b2454e6e246083d2a4df0a8b19dccc

I made some important changes to `FindMatlab.cmake`, which I want to suggest to the CMake project, but I want to make sure I don't miss something for Linux.

Many thanks!

**Comment by wcaarls** [comment]
It doesn't work, because my Matlab does not have a `cppMexFunction.map`. When I remove the line

```
list(APPEND _ver_map_files ${Matlab_EXTERN_LIBRARY_DIR}/cppMexFunction.map)
```

it works.

**Comment by crisluengo** [comment]
I have fixed up the `FindMatlab.cmake` script. Hopefully it works correctly now on all platforms. f3156b54f55e4f17b0a0c5c90f7b2d0ae2ed236a

It is strange, it looks like the C++ API symbols (`cppMexFunction.map`) are not explicitly exported under Linux. This might be an oversight. They're relying on `-fvisibility=default` being set when compiling (which is the default). If you add `-fvisibility=hidden` to the compile options for the `mex` command, things break (they didn't used to). This certainly indicates a bug in the `<mex.h>` file. It doesn't make any sense for `MW_NEEDS_VERSION_H` needing to be defined, and the `mex` command doesn't define it. I'll submit a bug report, I guess...

**Comment by wcaarls** [comment]
Works on Matlab R2018b under Ubuntu 18.04 and Matlab R2016a under Ubuntu 16.04.

**Comment by crisluengo** [comment]
Thank you so much!
