### ISSUE TITLE
Python 3.12 wheels on PyPI (and perhaps a new release?)

### ISSUE THREAD

**Issue by anntzer** [DIPlib/diplib#136]
**Component**
PyDIP.

**Describe the problem that this feature would solve**
Following the release of Python 3.12, it would be appreciated if you could provide wheels on PyPI for that version of Python, either for the previous (3.4.1) diplib release, or for a new one.  Thanks!

**Describe your suggested solution to the problem**
New wheels.

**Additional context**

**Comment by crisluengo** [comment]
Yes, you are right, we should have added 3.12 to the list before making the release.

I'll try to get this done soon(ish).

**Comment by crisluengo** [comment]
There's Python 3.12 wheels available now for all supported platforms.

**Comment by anntzer** [comment]
Thanks for the extremely fast reply!
