### ISSUE TITLE
Win10 x64 DIPlib compilation error 

### ISSUE THREAD

**Issue by AndreZeug** [DIPlib/diplib#140]
I followed the instructions on https://diplib.org/diplib-docs/building_windows.html, downloaded and installed all components (latest version) and failed at the point BUILDING  "Right-click on INSTALL and select “Build”."  

ERROR code [MSB3073](https://learn.microsoft.com/en-us/visualstudio/msbuild/errors/msb3073?view=vs-2022&f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(MSBuild.Exec.CommandFailed)%26rd%3Dtrue)
The command "setlocal
"C:\Program Files\CMake\bin\cmake.exe" -DBUILD_TYPE=Release -P cmake_install.cmake
if %errorlevel% neq 0 goto :cmEnd
:cmEnd
endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
:cmErrorLevel
exit /b %1
:cmDone
if %errorlevel% neq 0 goto :VCEnd
:VCEnd" exited with code 1.	INSTALL	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets	166		

**Output**
[output.txt](https://github.com/DIPlib/diplib/files/13798628/output.txt)

**CMake 3.28.1** 
![CMake_2023-12-30 173355](https://github.com/DIPlib/diplib/assets/20279594/162c892f-b0c4-4a78-a3f3-a48cfb52b9c2)

Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19045.
~~~Configuring Zlib~~~
~~~
~~~Configuring libics~~~
~~~Configuring LibTIFF~~~
LibTIFF uses win32 IO: TRUE
LibTIFF has JPEG 8/12 bit dual mode: FALSE
~~~
Could NOT find FFTW3 (missing: FFTW3_INCLUDE_DIR FFTW3_LIBRARY_FFTW3F FFTW3_LIBRARY_FFTW3) 
Could NOT find Freetype (missing: FREETYPE_LIBRARY FREETYPE_INCLUDE_DIRS) 
Could NOT find Java (missing: Java_JAVA_EXECUTABLE Java_JAVAC_EXECUTABLE Java_JAR_EXECUTABLE Java_JAVADOC_EXECUTABLE Java_JAVAH_EXECUTABLE Development) (Required is at least version "1.7")
Could NOT find FreeGLUT (missing: FREEGLUT_LIBRARY FREEGLUT_INCLUDE_DIR) 
FreeGLUT not found
Could NOT find GLFW (missing: GLFW_LIBRARY GLFW_INCLUDE_DIR) 
GLFW not found
Could NOT find PythonInterp (missing: PYTHON_EXECUTABLE) (Required is at least version "3.6")

--------------------------------------
   DIPlib CONFIGURATION REPORT

 * PROJECT_VERSION: 3.4.1
 * DIP_COPYRIGHT_YEAR: 2023
 * C++ compiler: MSVC 19.38.33133.0
 * Building shared library
 * Library installed to: z:\GIT\DIPlib\/bin
 * Binaries installed to: z:\GIT\DIPlib\/bin
 * Import library installed to: z:\GIT\DIPlib\/lib
 * Header files installed to: z:\GIT\DIPlib\/include
 * dox++ program not configured, no documentation can be generated
 * Using OpenMP for multithreading
 * Stack trace recording enabled
 * Asserts disabled
 * Unicode support enabled
 * Using 64-bit PRNG
 * ICS file IO enabled, with zlib
 * TIFF file IO enabled, with zlib, with JPEG
 * JPEG file IO enabled
 * Using PocketFFT
 * Not using FreeType
 * Unit test code included
 * DIPviewer module added to 'all' with window managers: 
 * DIPviewer Java bindings not configured
 * DIPJavaio module not configured
 * PyDIP module not configured
 * DIPimage toolbox added to 'all' target
 * DIPimage toolbox compiled for MATLAB R2023b
 * DIPimage toolbox installed to: z:\GIT\DIPlib\/share/DIPimage
 * DIPimage User Manual cannot be created (dox++ program not configured)

--------------------------------------

Configuring done (1.0s)
Generating done (1.8s)

**Component**
Select one or more of: DIPlib / DIPviewer / CMake build scripts.
Include the release version (3.4.1) 

**Describe the bug**
A clear and concise description of what the bug is. Include a description of observed results and expected results.

**To Reproduce**
Clean Win10 system, including Matlab R2023b
installed 
- Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.8.3
- CMake 3.28.1
- glfw-3.3.9.bin.WIN64 -> "Extract the ZIP file and note the location." **But what to do with it?**
- TODO: Describe how to get FFTW3. **Is it required? Where to find?**

**System information:**
 - Windows 10
  - If DIPimage, what version of MATLAB do you have? (type `ver` at the MATLAB command prompt, and copy-paste the result here).
 ->> ver
-----------------------------------------------------------------------------------------------------
MATLAB Version: 23.2.0.2459199 (R2023b) Update 5
MATLAB License Number: 40567690
Operating System: Microsoft Windows 10 Enterprise Version 10.0 (Build 19045)
Java Version: Java 1.8.0_202-b08 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
-----------------------------------------------------------------------------------------------------
MATLAB                                                Version 23.2        (R2023b)
Bioinformatics Toolbox                                Version 23.2        (R2023b)
Computer Vision Toolbox                               Version 23.2        (R2023b)
Curve Fitting Toolbox                                 Version 23.2        (R2023b)
DIPimage, a scientific image analysis toolbox         Version 2.9                 
DIPlib, a scientific image analysis library           Version 2.9                 
Deep Learning Toolbox                                 Version 23.2        (R2023b)
Global Optimization Toolbox                           Version 23.2        (R2023b)
Image Processing Toolbox                              Version 23.2        (R2023b)
Medical Imaging Toolbox                               Version 23.2        (R2023b)
Optimization Toolbox                                  Version 23.2        (R2023b)
Parallel Computing Toolbox                            Version 23.2        (R2023b)
Signal Processing Toolbox                             Version 23.2        (R2023b)
Statistics and Machine Learning Toolbox               Version 23.2        (R2023b)
Wavelet Toolbox                                       Version 23.2        (R2023b)

**Comment by AndreZeug** [comment]
Update, when adding 
GLFW_INCLUDE_DIR      Z:/GIT/GLFW/glfw-3.3.9.bin.WIN64/include
GLFW_LIBRARY              Z:/GIT/GLFW/glfw-3.3.9.bin.WIN64/lib-vc2022/glfw3.lib

I receive 42 ERRORS, the original persists 🙈
[output2.txt](https://github.com/DIPlib/diplib/files/13798705/output2.txt)

**Comment by crisluengo** [comment]
You have a long series of warning messages and then an error while parsing cmake_install.cmake. This is a file generated by CMake itself, so this makes very little sense. Unless you have two different versions of CMake on your system, and you used one to configure DIPlib, but then at build time it's using the other one.

I don't know how to check for this case, I'm not terribly comfortable using Windows.

Could MSVC come with a copy of CMake?

---

Don't worry about FFTW3, you don't need it. It's faster than the built-in FFT, but it's not that much of a difference.

---

The first error message compiling in the second output is consistent with an issue with CMake. You could have a syntax error there if the macro `STRIP_SIZE_DEFAULT` is not defined. It should be defined when invocating the compiler, and CMake is in charge of doing so.

**Comment by AndreZeug** [comment]
Moin Chris,
Oh yeah, you are absolutely right, when installing MS Visual Studio I did select the package "Desktop development with C++" (thought this was told by your installation guide) which then installs a bunch of tools including CMake
![grafik](https://github.com/DIPlib/diplib/assets/20279594/993b4b3f-9293-4dce-9254-4270258e75c9)

Need to check if I succeed when I uninstall the one (MSVS CMake) or the other (individually installed CMake)

**Comment by AndreZeug** [comment]
Uninstalling MSVS "Desktop development with C++" package causes serious errors 😪

![grafik](https://github.com/DIPlib/diplib/assets/20279594/973a0756-5db6-476f-9568-f35da066f1d7)

**Comment by AndreZeug** [comment]
🥳

Thanks Cris!
I cannot exactly tell why, but after reinstalling MSVS "Desktop development with C++" package, and gently restarting Win10 (unfortunately still a recommended habit using Windows 🙈) I succeed. 
![grafik](https://github.com/DIPlib/diplib/assets/20279594/3c09099b-0dea-4ac3-a8ef-99ce713bc055)

**Conclusion**
The description in [Building the DIPlib project on Windows](https://diplib.org/diplib-docs/building_windows.html) is correct / it works, but patience might help avoiding trouble after installing all components and a Windows typical restart might help before [Creating Visual Studio project files](https://diplib.org/diplib-docs/building_windows.html#windows_configure)

**Comment by crisluengo** [comment]
Wonderful! Happy you got it to work.

Reinstalling MSVC means you installed it *after* installing CMake, could that have an influence?
