### ISSUE TITLE
Can't import PyDIP intro Python script

### ISSUE THREAD

**Issue by HRGaitan** [DIPlib/diplib#15]
Hello there!

I'm using Linux on a ODROID, followed the building instructions for this library, it appears to have built succesfully but when trying to import it I got the error "No modue named PyDIP". 

Is there a detailed guide for building this library? 

Thanks in advance.

**Comment by crisluengo** [comment]
Please see the comment here: https://github.com/DIPlib/diplib/issues/14#issuecomment-427720180

Let us know if that solves your issue. It'd be great to hear about your experiences on that device, so far I've only had people use the library on desktops.

This is something we'd like to fix in the installation script, but haven't gotten around to yet. If you know how to solve this better, please submit a pull request!

**Comment by HRGaitan** [comment]
Indeed, adding that system path at the beginning of the code solved the issue.
Just run a test and worked wonderful! Faster than I expected.

I thank you very much for your help.
