### ISSUE TITLE
Fails to build on i386: error: constructor cannot be redeclared

### ISSUE THREAD

**Issue by yurivict** [DIPlib/diplib#162]
**Component**
n/a

**Describe the bug**
```
In file included from /wrkdirs/usr/ports/graphics/diplib/work/diplib-3.5.0/src/analysis/chord_length.cpp:31:
In file included from /wrkdirs/usr/ports/graphics/diplib/work/diplib-3.5.0/include/diplib/regions.h:26:
In file included from /wrkdirs/usr/ports/graphics/diplib/work/diplib-3.5.0/include/diplib/measurement.h:30:
/wrkdirs/usr/ports/graphics/diplib/work/diplib-3.5.0/include/diplib/label_map.h:62:16: error: constructor cannot be redeclared
      explicit LabelMap( std::vector< dip::uint > const& labels ) {
               ^
/wrkdirs/usr/ports/graphics/diplib/work/diplib-3.5.0/include/diplib/label_map.h:54:16: note: previous definition is here
      explicit LabelMap( std::vector< LabelType > const& labels ) {
               ^
6 warnings and 1 error generated.
```

[log](https://pkg-status.freebsd.org/beefy21/data/140i386-default/2517bfad2ac6/logs/diplib-3.5.0.log)

**To Reproduce**
regular build

**System information:**
 - What OS do you have? FreeBSD 14.1
 - If PyDIP, what version of Python do you have?
 - If DIPimage, what version of MATLAB do you have? (type `ver` at the MATLAB command prompt, and copy-paste the result here).
 - If compiled from sources, what compiler and version did you use? clang-18

**Comment by crisluengo** [comment]
I'm guessing you have a 32-bit system? I hadn't thought of that... We should add a 32-bit build on the CI.

**Comment by yurivict** [comment]
i386 is 32-bit system.

**Comment by crisluengo** [comment]
There seems to be a similar issue with the two definitions of `GetLabelBoundingBox()`. I'll look into that one in the morning.

**Comment by crisluengo** [comment]
@yurivict Thank you for reporting this!
The library now builds on with `gcc -m32` on GitHub CI. I'm expecting you'll be able to build on your machine now.

There are a few tests that are failing now. I will look into that over the coming days.

**Comment by yurivict** [comment]
@crisluengo 
Thanks! I will test it once the next version would come out.

**Comment by crisluengo** [comment]
@yurivict I've made a new release.
