### ISSUE TITLE
PyDIP: 3d TIFFs are loaded as 2d

### ISSUE THREAD

**Issue by AlexanderZeilmann** [DIPlib/diplib#165]
**Describe the bug**
When reading a 3d TIFF file with PyDIP only a 2d slice is loaded

**To Reproduce**
```
import diplib as dip
img = dip.ImageReadTIFF('3d.tif')
```

Result:
```
2D Scalar image:
    data type:      UINT8
    sizes:          {470, 481}
    strides:        {1, 470}, tensor stride 1
    data pointer:   0x1280c8000 (shared among 1 images)
    origin pointer: 0x1280c8000
```

**System information:**
 - macOS
 - Python 3.11.9
 - pydip 3.4.1

Do I have to do anything else to load 3d TIFFs?

**Comment by crisluengo** [comment]
See, formally there’s no such thing as a 3D TIFF… A TIFF file can contain multiple 2D images, each one in its own “page”. There is no need for those pages to have any relationship to each other, or to even have the same size. Some scanner software will write multiple scanned pages of text as individual pages in the same TIFF file. Some whole slide scanners will write the whole slide in multiple resolutions to separate pages, a so-called pyramid. Some confocal microscopes will write the 2D slices of a 3D image as separate pages. Unless you know in advance what is written to the file, you don’t know how to read it. This DIPlib function takes the simple approach of having the user specify how to read the file.

I think the documentation, though short, does make this clear. https://diplib.org/diplib-docs/file_io.html#dip-ImageReadTIFF-Image-L-String-CL-Range--RangeArray-CL-Range-CL-String-CL

Bio-Formats uses some internal logic to decide if the pages belong to the same 3D image, and considers those pages to be the same image. You can use Bio-Formats from within DIPlib using [the DIPjavaio module](https://diplib.org/diplib-docs/dipjavaio.html#dip-javaio-ImageReadJavaIO-Image-L-String-CL-String-CL-dip-uint-). See [here](https://diplib.org/diplib-docs/pydip_user_manual.html#pum_dipjavaio) for Python-specific instructions.

---

As an aside, TIFF is an open standard that can easily be extended for particular uses. I have seen a system that writes 3D images as a single page, inventing its own (non-standard) depth tag, and writing 3D blocks of the image as 3D “tiles”. DIPlib is not able to read such non-standard TIFF files.

**Comment by AlexanderZeilmann** [comment]
Thank you for your extensive answer. Makes complete sense 🙂 

> I think the documentation, though short, does make this clear.

You are absolutely right. My stupid mistake was was that I only saw the summary part at the top of the documentation page and did not recognize that the orange parts are links that lead to a more extensive documentation. 🙈 
![dip](https://github.com/DIPlib/diplib/assets/901391/d6083296-a171-484c-90e4-3ad6a4c4df15)
