### ISSUE TITLE
Unnecessary text printed on package import

### ISSUE THREAD

**Issue by kji2j0sdi2jojfkjha3289** [DIPlib/diplib#166]
First of all, thanks for authoring `diplib`!

**Component**
Select one or more of: PyDIP 3.3.0

**Describe the bug**
Text is printed to the console upon running `import diplib` in an interactive python session (e.g. `python`, notebooks, etc.).

This unnecessarily clutters my session. The main python codebase I work with is a large monorepo that imports hundreds distinct packages. If each of them printed 3 lines on import like diplib does, then I would have to scroll through over a thousand lines at the top of every python session that imports the codebase.

I would ask that this text no longer be printed upon import.

**To Reproduce**
While in an interactive python session:
```python
>>> import diplib
DIPlib -- a quantitative image analysis library
Version 3.3.0 (May 21 2022)
For more information see https://diplib.org
```

**Comment by crisluengo** [comment]
This works as intended.

If you **really** want to avoid output to console, you can do something like this:
```
import sys
tmp = sys.ps1
del sys.ps1
import diplib as dip
sys.ps1 = tmp
```
This makes DIPlib think it's not running in an interactive session.

If you have any suggestions to make this easier, a PR is welcome. But we do not want to skip the output by default.

**Comment by kji2j0sdi2jojfkjha3289** [comment]
Thanks for the response @crisluengo! I just wanted to reiterate that if I had to do that for every single package I imported, it would be a real pain! I think I'll just work to remove diplib as a dependency. Thanks!
