### ISSUE TITLE
compiling on raspberry pi (armV6) hangs on 83% riesz.ccp.o

### ISSUE THREAD

**Issue by modernecotech** [DIPlib/diplib#17]
trying to compile the latest beta on a raspberry pi with GCC V 6.3. 

It has LibTIFF / FFTW3
CMAKE goes without a hitch

**Comment by crisluengo** [comment]
The file `reisz.cpp` is short and contains straight-forward code. I'm not sure why the compiler would hang there. It might be coincidental. Is the system thrashing (i.e. swapping out virtual memory to disk) when it hangs?

The file `Python.h` should come with Python. Maybe on the Raspberry Pi platform you need to install the development files for Python separately?

**Comment by modernecotech** [comment]
that gave me a clue. python3-dev was not installed. will try again now.

**Comment by modernecotech** [comment]
sadly it went nowhere. its on a clean raspbian installation with the latest debian distribution. it is armv6 though.

**Comment by modernecotech** [comment]
internal compiler error recipe for target matrix.cpp.o failed  
error 4

**Comment by crisluengo** [comment]
`matrix.cpp` is a complicated file to compile, it contains most of the code that uses Eigen, which is very heavy on templates. This one file takes about 10 times as long to compile on my machine compared to the next most complex one. I’m not surprised you’re running out of memory on that one.

Maybe there is a way to cross-compile on a Linux desktop for the ARM chip?

**Comment by crisluengo** [comment]
Are you using `make -j4` or similar? If so, did you try `make -j1` instead? That ensures single-threaded compilation, would save tons of memory.

**Comment by modernecotech** [comment]
I was doing make -j to make it super fast... 

I shall retry with make -j1 and let it simmer overnight.

**Comment by modernecotech** [comment]
Hi 

make -j1 
make -j1 install 

worked! I have a working PyDIP on raspberry Pi ARMv6 now.

**Comment by crisluengo** [comment]
Wonderful!
