### ISSUE TITLE
Error in Building Library -Window

### ISSUE THREAD

**Issue by manishspm09** [DIPlib/diplib#19]
Using following source to build PyDIP library for Python.
https://github.com/DIPlib/diplib.git

While building PyDIP library through CMake and Visual Studio - CMakeError text Document is generated in target directory. Due to this error i assume I am only finding DIP.dll in target directory:
C:\Users\<name>\DIPlib\lib.

Errors:
1. PyDIP is imported first time but after that it gives error ;

  File "C:\Users\Manish\Anaconda3\lib\site-packages\PyDIP\__init__.py", line 66, in <module>
    from PyDIP.PyDIP_bin import *

ImportError: DLL load failed: The specified module could not be found.

2. Though first time PyDIP is imported - dip.Gauss or any other dip.function is not found in built library.

**System information:**
 - OS: Windows 10 Home, 64 bit
 - Python 3.6.3

**Comment by crisluengo** [comment]
Please try this to import PyDIP:
```
import os
os.environ["PATH"] += os.pathsep + "C:\Users<name>\DIPlib\lib"
import PyDIP as dip
```
(make sure to fill in the correct path there, to where you installed the DIP.dll shared library).

It seems this bit disappeared again from the Windows installation instructions...

**Comment by crisluengo** [comment]
I have made some changes to the PyDIP `__init__` script, it should now automatically set the `PATH` variable on Windows machines. The suggestion in the previous comment should no longer be necessary.

Could you please pull these recent changes and rebuild the project? I don't have access to a Windows computer, and therefore need your help to verify that this change fixes this issue. I would be most grateful!

**Comment by manishspm09** [comment]
Sorry for the delay, still getting few errors

Two errors:
1. CMake error -
C:\Users\Manish\Desktop\Python\Library\Target\CMakeFiles\CMakeTmp\src.cxx(1): error C2065: '__PRETTY_FUNCTION__': undeclared identifier [C:\Users\Manish\Desktop\Python\Library\Target\CMakeFiles\CMakeTmp\cmTC_6fac9.vcxproj]

Done Building Project "C:\Users\Manish\Desktop\Python\Library\Target\CMakeFiles\CMakeTmp\cmTC_6fac9.vcxproj" (default targets) -- FAILED.



Build FAILED.

2. In CMake under DIP - DIP_ENABLE_ICS is there but DIP_ENABLE_TIFF is not there.
DIPlib was compiled without TIFF support.
in function: ImageReadTIFF (C:\Users\Manish\Desktop\Python\Library\Source\src\file_io\tiff_read.cpp at line number 1147)
Also can we use other image formats in this library?

![image](https://user-images.githubusercontent.com/46446249/51108312-c7635100-1817-11e9-9e7b-05491336b87a.png)

**Comment by crisluengo** [comment]
1. This seems like an issue with CMake. Is there any more information generated in the log file? (`CMakeFiles/CMakeError.log`, also `CMakeFiles/CMakeOutput.log`). We do test to see if your compiler knows `__PRETTY_FUNCTION__`. CMake then compiles a little test program, if this compilation step generates an error then your compiler doesn't know this macro. But an error here is supposed to be caught and not cause any user-visible errors.

2. To enable TIFF, look [here](https://github.com/DIPlib/diplib/blob/master/INSTALL_Windows.md). In short, you need to download LibTIFF and compile it (I haven't tried with binary distributions on Windows), then configure the paths in CMake by clicking on the "Advanced" check box just above the list of Name/Value parameters, and filling out `TIFF_INCLUDE_DIR` and `TIFF_LIBRARY_RELEASE`. You should do the same for ZLib if you want complete ICS support.

    We only have built-in support for TIFF and ICS because these are commonly used in the areas of application of DIPlib, and support elsewhere is poor (most image file software doesn't support ICS at all, and doesn't support sufficient features for TIFF). For other file formats it is easy to use image import tools. For example, in Python you have `matplotlib.pyplot.imread`, which supports quite a few formats. You'll be able to put its output (a NumPy array) directly into any PyDIP function as an image. In fact, PyDIP images are fully compatible with NumPy arrays and any other "array-like" object. If you work with microscopy data, consider using BioFormats, there's [a Python bridge](https://github.com/CellProfiler/python-bioformats).

**Comment by manishspm09** [comment]
Hi, Thanks for your reply. Please find below the log files.

[CMakeError.log](https://github.com/DIPlib/diplib/files/2758069/CMakeError.log)
[CMakeOutput.log](https://github.com/DIPlib/diplib/files/2758070/CMakeOutput.log)

**Comment by crisluengo** [comment]
@manishspm09, I see errors there for things that are supposed to generate errors. Are you not getting a Visual Studio project when you click on "Generate"? Were you not seeing these errors when you compiled the project the first time, before my update?

**Comment by manishspm09** [comment]
I am able to use the library and its function. The results for image analysis is amazing. Thanks for helping me with the library. 
These errors were there before your update. Getting visual studio project
Thanks
