### ISSUE TITLE
missing -lpthread on building examples

### ISSUE THREAD

**Issue by b-guerra** [DIPlib/diplib#2]
I have been trying to build this up the whole day, and I think I`m pretty close to make it.

However, I believe I found an error.

`/usr/bin/ld: CMakeFiles/viewer.dir/examples/viewer.cpp.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'`

**Comment by crisluengo** [comment]
Bruno, on which operating system are you compiling? Is it Linux? I never got this error, but it's been a long time since I last compiled the examples on Linux. On MacOS with GCC this is not necessary (builds and runs fine without), and on Windows adding `-lpthread` will probably break things.

**Comment by crisluengo** [comment]
Relevant info for future reference:
- [What are the correct link options to use std::thread in GCC under linux?](https://stackoverflow.com/q/8649828/7328782)
- [clang's linker doesn't like -pthread](https://github.com/mesonbuild/meson/issues/2628)

**Comment by b-guerra** [comment]
Yes! It was on Linux Cris, Ubuntu 16.04.

I am running it now without any problems 😊

Maybe it would be useful to check if the OS is Linux, add the the -lpthread to the lib flags I wonder? hmm

Anyway, thank for the relevant info!

Hope you had an awesome weekend!

Cheers

________________________________
De: Cris Luengo <notifications@github.com>
Enviado: domingo, 14 de janeiro de 2018 04:36
Para: DIPlib/diplib
Cc: Bruno Guerra; Author
Assunto: Re: [DIPlib/diplib] missing -lpthread on building examples (#2)


Bruno, on which operating system are you compiling? Is it Linux? I never got this error, but it's been a long time since I last compiled the examples on Linux. On MacOS with GCC this is not necessary (builds and runs fine without), and on Windows adding -lpthread will probably break things.

**Comment by wcaarls** [comment]
https://stackoverflow.com/questions/1620918/cmake-and-libpthread

Suggests

set(THREADS_PREFER_PTHREAD_FLAG ON)
find_package(Threads REQUIRED)
target_link_libraries(my_app Threads::Threads)

**Comment by crisluengo** [comment]
Does linking to `Threads::Threads` set compiler option too?

In `man gcc`, for the `-pthread` linker option, it says:
> On some targets this option also sets flags for the preprocessor, so it should be used consistently for both compilation and linking.

See also: https://stackoverflow.com/q/2127797/7328782

Ah, nevermind, I see this in `FindThreads.cmake`

    set_property(TARGET Threads::Threads PROPERTY INTERFACE_COMPILE_OPTIONS "-pthread")
