### ISSUE TITLE
PyDIP, where should it go from here?

### ISSUE THREAD

**Issue by crisluengo** [DIPlib/diplib#25]
Currently *PyDIP* is a thin wrapper around the *DIPlib* library. Some things are still rather awkward. For example:
-  `dip.Image` doesn't have an iterator.
- Conversion of an RGB image read through `pyplot` yields a vector image without color space information (solutions: assume RGB if there are 3 tensor elements? write a `dip.readim` function?).
- Parameters that require an array (e.g. `dip.Gauss`' `sigma` input) cannot handle a scalar.
- etc. etc.

In short, we need lots of usage, lots of feedback from users, and lots of time polishing the interface.

But ideally we'd take this to a different level, in a way similar to what *DIPimage* is. For example, we could write a GUI as exists in *DIPimage*. And maybe make the module more "Pythonic" by changing function names.

We also need to find a way to automatically generate documentation from Doxygen. One approach is [here](https://stackoverflow.com/q/34896122/7328782).

**Comment by Wicloz** [comment]
Worth mentioning with regard to PyDIP is that a small selection of functions, such as `PeronaMalikDiffusion`, use `lambda` as a keyword argument. Python does not support this.

**Comment by crisluengo** [comment]
@Wicloz Indeed, `lambda` is a keyword in Python. I'll rename the parameter.

Thanks!

**Comment by wcaarls** [comment]
Some random musings:

* Documentation

  There should be more of it.
  
  `GaussianNoise` is documented as requiring `random`, but does not (at least in PyDIP).

* Convert data type
  
  ```
  a = dip.Image((256, 256), dt='UINT8')
  b = dip.Image(a, dt='UINT8')
  ```

  The second fails

* Advanced indexing

  ```
  a = dip.Image((256, 256))
  print(a[0,[1, 3]])
  print(np.asarray(a)[0,[1, 3]])
  ```

  The first fails

* Tensor indexing

  Maybe use `a(0)` instead of `a.TensorElement(0)`?

* Tensor vs dimension when converting from numpy

  ```
  dip.Image(np.zeros((256, 256, 9)))  # Tensor image
  dip.Image(np.zeros((256, 256, 10))) # 3D image
  ```

  How to do this consistently?

* Passing empty images

  ```
  dip.Mean(a, dip.Image())
  ```

  Should be able to be written as (one of?)

  ```
  dip.Mean(a, ())
  dip.Mean(a, [])
  dip.Mean(a, None)
  ```

**Comment by crisluengo** [comment]
Should we rewrite indexing so it is done entirely in Python? I think that's the only way we're going to get indexing syntax that matches Python's. The conversion to/from a NumPy array is essentially free, so there's no major overhead there.

To convert data type, you can use `dip.Convert`. Your syntax doesn't exist in C++, and hence it's not currently present in the Python interface. I guess we could add that option to the constructor to match the functionality in DIPimage.

If you want to add or improve anything in the Python interface, go ahead! There's lots of work there! :)

**Comment by wcaarls** [comment]
> Should we rewrite indexing so it is done entirely in Python? I think that's the only way we're going to get indexing syntax that matches Python's. The conversion to/from a NumPy array is essentially free, so there's no major overhead there.

I assume we still want `a[x, y, z]` indexing, right, instead of `a[y, x, z]`? The question is, do we want to index tensor elements as `a[...,1]`/`a[1,...]` or as `a(1)[...]`? The first one can be assigned to...

> To convert data type, you can use dip.Convert. Your syntax doesn't exist in C++, and hence it's not currently present in the Python interface. I guess we could add that option to the constructor to match the functionality in DIPimage.

Maybe, but `Convert` is fine. I must admit it is difficult to keep all functions in my head sometimes.

> If you want to add or improve anything in the Python interface, go ahead! There's lots of work to do there! :)

I'm thinking about it :-) 

I'll see if I can tackle some of the easier stuff first.

* What do you think about `a(0)` instead of `a.TensorElement(0)`? 
* I'm thinking of changing the higher dimension ordering in `BufferToImage`. I think it should go `[y, x, z, w]` instead of `[w, z, y, x]`; how about you?
* The tensor/spatial magic could be kept as is, with additional `dip.SpatialImage` and `dip.TensorImage` functions?

**Comment by crisluengo** [comment]
> I assume we still want `a[x, y, z]` indexing, right, instead of `a[y, x, z]`? The question is, do we want to index tensor elements as `a[...,1]`/`a[1,...]` or as `a(1)[...]`? The first one can be assigned to...

I don't like mixing tensor and spatial dimensions in indexing. Separating these out in DIPimage way back when was a good idea, I found it improved code logic quite a lot, and made working with color images easier for the uninitialized (i.e. those that hadn't yet gotten used to the `[...,1]` way).

This works:

    b.TensorElement(0)[:,:] = a

I guess `b(0)[:,:]` is quite OK. `b[:,:](0)` would then work also, but wouldn't be assignable?

So the DIPimage syntax `b{1}(2,3)` is translated to Python as `b(0)[1,2]`. It'll be a bit getting used to, but it is shorter than the `TensorElement()` function.

Something like `b[0][:,:]` could be made to work as well, but I guess you'd always have to specify the tensor indexing? Because we can't have `b[0]` be ambiguous.

> * I'm thinking of changing the higher dimension ordering in `BufferToImage`. I think it should go `[y, x, z, w]` instead of `[w, z, y, x]`; how about you?

I thought NumPy did `[w, z, y, x]`, which is why it's implemented in that way. If I'm wrong about that, feel free to fix it. `[y, x, z, w]` sounds very MATLABy.

> * The tensor/spatial magic could be kept as is, with additional `dip.SpatialImage` and `dip.TensorImage` functions?

Sounds good. `dip.TensorImage` would be `dip.SpatialImage` plus a call to `dip.SpatialToTensor`.
For `dip.SpatialImage` to trick `dip.Image` into not casting a short dimension to the tensor dimension, you could simply add a dimension of size 1 to the matrix.

**Comment by crisluengo** [comment]
> * Passing empty images
>   ```
>   dip.Mean(a, dip.Image())
>   ```
>  
>   Should be able to be written as (one of?)
>   ```
>   dip.Mean(a, ())
>   dip.Mean(a, [])
>   dip.Mean(a, None)
>   ```

`None` seems the cleanest here. But it's explicitly disallowed in Pybind11.
https://github.com/pybind/pybind11/issues/642#issuecomment-634961927

**Comment by wcaarls** [comment]
> So the DIPimage syntax b{1}(2,3) is translated to Python as b(0)[1,2]. It'll be a bit getting used to, but it is shorter than the TensorElement() function.

Right. And I didn’t even think about b(0)[...] being assignable, I was hung up on b(0) not being.

> I thought NumPy did [w, z, y, x], which is why it's implemented in that way. If I'm wrong about that, feel free to fix it. [y, x, z, w] sounds very MATLABy.

I don’t think numpy cares much, except that it prints the first index vertically. It is disconnected from the storage order, which can be chosen by the user. I’ll figure out what imageio does and make sure the conversion to and from that is easy.

> None seems the cleanest here. But it's explicitly disallowed in Pybind11.

I came across that issue. Let’s see what they suggest. We could always allow it in the DIPlib repo, but it would be nice to know what the consequences are.

**Comment by wcaarls** [comment]
I did not find any issues with the py::none change when running the standard examples. I therefore suggest the following patch:

```diff
 dependencies/pybind11/include/pybind11/cast.h |  4 ++--
 pydip/src/PyDIP_py.py                         | 25 +++++++++++++++++++++++++
 pydip/src/image.cpp                           | 22 ++++++++++++++++------
 3 files changed, 43 insertions(+), 8 deletions(-)

diff --git a/dependencies/pybind11/include/pybind11/cast.h b/dependencies/pybind11/include/pybind11/cast.h
index 605acb36..70aa770c 100644
--- a/dependencies/pybind11/include/pybind11/cast.h
+++ b/dependencies/pybind11/include/pybind11/cast.h
@@ -642,8 +642,8 @@ public:
         if (src.is_none()) {
             // Defer accepting None to other overloads (if we aren't in convert mode):
             if (!convert) return false;
-            value = nullptr;
-            return true;
+            //value = nullptr;
+            //return true;
         }
 
         auto &this_ = static_cast<ThisT &>(*this);
diff --git a/pydip/src/PyDIP_py.py b/pydip/src/PyDIP_py.py
index 69994e57..6b540d30 100644
--- a/pydip/src/PyDIP_py.py
+++ b/pydip/src/PyDIP_py.py
@@ -153,3 +153,28 @@ def Show(img, range=(), complexMode='abs', projectionMode='mean', coordinates=()
 
 
 PyDIP.Image.Show = Show
+
+
+def ScalarImage(a):
+   """Convert numpy.ndarray to scalar PyDIP.Image"""
+   img = PyDIP.Image(a)
+   if img.TensorElements() > 1:
+      if img.TensorStride() > 1:
+         img.TensorToSpatial(img.Dimensionality())
+      else:
+         img.TensorToSpatial(0)
+   return img
+
+
+def TensorImage(a, axis=-1):
+   """Convert numpy.ndarray to column tensor PyDIP.Image
+
+   Keyword arguments:
+   axis -- array axis to convert to Tensor; defaults to the last axis.
+   """
+   img = SpatialImage(a)
+   axis = -axis - 1
+   if axis < 0:
+     axis += img.Dimensionality()
+   img.SpatialToTensor(axis)
+   return img
diff --git a/pydip/src/image.cpp b/pydip/src/image.cpp
index b39f3f7b..e0be4ff9 100644
--- a/pydip/src/image.cpp
+++ b/pydip/src/image.cpp
@@ -112,9 +112,13 @@ dip::Image BufferToImage( py::buffer& buf ) {
    }};
    // Create an image with all of this.
    dip::Image out( dataSegment, info.ptr, datatype, sizes, strides, {}, 1 );
-   // If it's a 3D image and the first dimension has <10 pixels, let's assume it's a tensor dimension:
-   if(( sizes.size() > 2 ) && ( sizes[ 0 ] < 10 )) {
-      out.SpatialToTensor( 0 );
+   // If it's a 3D image and the first or last dimension has <10 pixels, let's assume it's a tensor dimension:
+   if(( sizes.size() > 2 ) && ( sizes[ 0 ] < 10 || sizes[ ndim-1 ] < 10 )) {
+      if ( sizes[ 0 ] < sizes[ ndim - 1 ]) {
+         out.SpatialToTensor( 0 );
+      } else {
+         out.SpatialToTensor( ndim-1 );
+      }
    }
    return out;
 }
@@ -222,6 +226,8 @@ void init_image( py::module& m ) {
    auto img = py::class_< dip::Image >( m, "Image", py::buffer_protocol(), "The class that encapsulates DIPlib images of all types." );
    // Constructor for raw (unforged) image, to be used e.g. when no mask input argument is needed
    img.def( py::init<>() );
+   img.def( py::init([](py::none const& ) { return dip::Image{}; }), "none"_a );
+   py::implicitly_convertible< py::none, dip::Image >();
    // Constructor, generic
    img.def( py::init< dip::UnsignedArray const&, dip::uint, dip::DataType >(), "sizes"_a, "tensorElems"_a = 1, "dt"_a = dip::DT_SFLOAT );
    // Constructor that takes a Sample
@@ -354,9 +360,13 @@ void init_image( py::module& m ) {
    img.def( "Imaginary", []( dip::Image const& image ) -> dip::Image { return image.Imaginary(); } );
    img.def( "QuickCopy", &dip::Image::QuickCopy );
    // These don't exist, but we need to have a function for operation[] too
-   img.def( "TensorElement", []( dip::Image const& image, dip::sint index ) -> dip::Image { return image[ index ]; }, "index"_a );
-   img.def( "TensorElement", []( dip::Image const& image, dip::uint i, dip::uint j ) -> dip::Image { return image[ dip::UnsignedArray{ i, j } ]; }, "i"_a, "j"_a );
-   img.def( "TensorElement", []( dip::Image const& image, dip::Range const& range ) -> dip::Image { return image[ range ]; }, "range"_a );
+   img.def( "__call__", []( dip::Image const& image, dip::sint index ) -> dip::Image { return image[ index ]; }, "index"_a );
+   img.def( "__call__", []( dip::Image const& image, dip::uint i, dip::uint j ) -> dip::Image { return image[ dip::UnsignedArray{ i, j } ]; }, "i"_a, "j"_a );
+   img.def( "__call__", []( dip::Image const& image, dip::Range const& range ) -> dip::Image { return image[ range ]; }, "range"_a );
+   // NOTE: Compatibility with beta PyDIP. Remove?
+   img.def("TensorElement", [](dip::Image const& image, dip::sint index) -> dip::Image { return image[index]; }, "index"_a);
+   img.def("TensorElement", [](dip::Image const& image, dip::uint i, dip::uint j) -> dip::Image { return image[dip::UnsignedArray{ i, j }]; }, "i"_a, "j"_a);
+   img.def("TensorElement", [](dip::Image const& image, dip::Range const& range) -> dip::Image { return image[range]; }, "range"_a);
    // Copy or write data
    img.def( "Pad", py::overload_cast< dip::UnsignedArray const&, dip::String const& >( &dip::Image::Pad, py::const_ ), "sizes"_a, "cropLocation"_a = "center" );
    img.def( "Copy", py::overload_cast<>( &dip::Image::Copy, py::const_ ));
```

Question: should we remove the `TensorElement` method? I think it's cleaner to do so, but it will break existing code.

**Comment by crisluengo** [comment]
Awesome! Thanks!

I don't know what to do with the `TensorElement` method. I never really liked it, it was just an easy solution at the time. But it's hard to know how many people might be using the Python bindings by now.

**Comment by crisluengo** [comment]
Please create a branch. I'd like to test a few things as well. For example make sure things don't break if you put `None` in random places where it's not expected.

Also, I have some changes I want to add concerning raw images and zero-size NumPy arrays, that sort of goes together with the `None` change.

Fantastic that you implemented casting of scalars to `DimensionArray`. It would be good to do that for `dip::Pixel` too. Scalars cast to `dip::Sample`, and `dip::Sample` casts to `dip::Pixel`, but I don't know if both steps are applied in the interface.

Many thanks!

**Comment by wcaarls** [comment]
Ok! Let's make sure it works in all cases... 3571a8a28fc0d3f0ab51cd93f8bede64bcad800d .

**Comment by crisluengo** [comment]
I can't get your changes to `type_caster< dip::DimensionArray< Type >>` to compile. For some reason `value` and `value_conv` are not recognized by the compiler. You can see these errors on Travis as well, but only for MacOS: https://travis-ci.org/github/DIPlib/diplib/builds/692600861

**Comment by wcaarls** [comment]
I tried some things until Xcode was happy. Not sure why it needs this, though.

**Comment by crisluengo** [comment]
Weird that I had this issue with GCC on Mac, not Xcode.

I've pushed some more changes to this branch. The `DimensionArray` type caster change turned `dip.Image(50)` into the same as dip.Image([50]), creating a 1D image with 50 pixels, rather than a 0D image with the value 50. We now distinguish the two again by changing the order of the constructors (the first one that matches the signature is used). Plus, `Sample` implicitly converts to `Image`, so now we can do things like `dip.Modulo(out, 50)` instead of `dip.Modulo(out, dip.Image(50))`.

There no longer is a constructor that takes a `Pixel`, there was no way of distinguishing that from the one that takes a `DimensionArray`. If we ever make an interface to the `Pixel` class (rather than casting to/from a Python list), we can put that constructor back.

Also, things like `dip.Image(np.array((0,)))` and `np.array(dip.Image())` now work correctly.

**Comment by wcaarls** [comment]
Awesome! Do we want

```
dip.DrawBandlimitedBall(img, 30, (42, 60), 255, "filled", 5)
```

To work? In that case, scalars should cast to `Pixel` as well.

On as side note, I think we're going to need Python unit tests...

**Comment by crisluengo** [comment]
Yes, anything that makes usage easier is welcome.

And we certainly do need Python unit tests. Right now, Travis only compiles the Python interface on MacOS, the other 3 runs only compile DIPlib itself. So there's a lot to do to get to that point. But even if the tests are only run locally and on demand, it would help a lot when making important changes like the ones we're making here.

I've also been thinking about adding the `out` image argument to functions. What would it look like to have an optional `out` argument? Would that mean we'd have two different function signatures, like in C++? If someone passes a NumPy array for `out`, then it's cast to a `dip.Image`, this image must be `Protect`ed, otherwise the function could re-forge the image and write to something that is not the NumPy array. But the conversion function does't know it's an input or an output image. So what happens if we always protect images created from a buffer? Is there some place this could be problematic?

**Comment by wcaarls** [comment]
I committed the scalar to Pixel conversion. 77e33b9091d51cc961ee5b7536c65d53c42c5f47

I also tried Python's `doctest` on for size. I think it's quite a nice way of writing the tests; they can be used for reference as well. What do you think? cdb4675c983507faa59b1146cf84db8f3c342fb6

**Comment by crisluengo** [comment]
That’s an excellent way to write a test! Really cool. It might end up being a bit overly detailed in places, for a tutorial. But it’s a great way of ensuring that the documentation and the code don’t go out of synch. I really like that.

**Comment by wcaarls** [comment]
I integrated the unit tests into the build system. However, I had to disable `CMAKE_BUILD_WITH_INSTALL_RPATH`, otherwise `PyDIP_bin` cannot be loaded from the build tree. Do you have a solution for this?

**Comment by crisluengo** [comment]
It should be fine to disable that. I think I added it to make the install faster.
This was especially important when DIPimage had more than 100 MEX-files to re-link. We have a lot fewer now, so it's not such a big deal. Maybe we can `set_target_properties("mex-file", BUILD_WITH_INSTALL_RPATH ON)` or something like that?

**Comment by wcaarls** [comment]
Brilliant. I did the opposite:

```
set_target_properties(PyDIP_bin PROPERTIES BUILD_WITH_INSTALL_RPATH OFF)
```

**Comment by crisluengo** [comment]
@wcaarls : I've fixed the issue with the tensor iterator in cases of 0 stride: edbb27abae488e117f8c88f6f9506038d2100783

I've also rebased your branch [pydip-experimental](https://github.com/DIPlib/diplib/commits/pydip-experimental) onto master, and at the same time removed some "oops" commits. If you want to continue working on this branch, please `git pull --rebase`, or simply delete your local branch and then pull a new copy. I've merged most stuff into master, except the new Python testing. I'll let you tweak that some more first if you want. By the way, I moved the test files to a separate directory to avoid confusion.

We need to enable assertions in Travis so that they can fire during testing. One of your new Python tests failed an assertion inside DIPlib code, which brought to light a bug: 1520820aa514ee7efd3d0950c11f5939b2ad9d10

**Comment by wcaarls** [comment]
Great!

I think the current state can be merged to master, although it makes sense to keep the branch around for further development, such as on the `out` / `protect` question.

Enabling assertions on Travis sounds like a good idea, is it a matter of passing `-DDIP_ENABLE_ASSERT=ON` in the `script`?

**Comment by crisluengo** [comment]
Feel free to merge. I merged a portion because I wanted to change the order of some commits, and push out the bug fixes right away.

Yes, `-DDIP_ENABLE_ASSERT=ON` as a parameter to CMake.

I see that the Travis configure script installs `python3-dev` on Linux, but somehow this is not found by the CMake configuration script.

**Comment by wcaarls** [comment]
Merged. I'm not sure what to do with the current state of the `pydip-experimental` branch, though. I'd just delete it and rebranch from master, but I'm sure you have a better idea...

**Comment by crisluengo** [comment]
This should work:

    git checkout pydip-experimental
    git rebase master

If you get nasty conflicts, you can cancel and do

    git reset --hard HEAD~5  # or whatever number of commits
    git rebase master

**Comment by crisluengo** [comment]
Nice by the way that you got all that Travis stuff working. Thanks!

**Comment by wcaarls** [comment]
I really don't grok git yet. I ended up doing

```
git checkout pydip-experimental
git reset --hard master
git push --force
```

to make pydip-experimental equal to master.

Travis took some round trips, but worked in the end. Note though that Windows is now compiling in 64-bits.

**Comment by crisluengo** [comment]
A summary of what happened in this thread:

- `dip.Image` doesn't have an iterator.
    ➜ **It doesn't need one.**
- Conversion of an RGB image read through `pyplot` yields a vector image without color space information (solutions: assume RGB if there are 3 tensor elements? write a `dip.readim` function?).
    ➜ **This is still the case.**
- Parameters that require an array (e.g. `dip.Gauss`' sigma input) cannot handle a scalar.
    ➜ **Solved.**
- Documentation: There should be more of it.
    ➜ **There's a little bit more of it, but still way too little.**
- `GaussianNoise` is documented as requiring `random`, but does not in PyDIP.
    ➜ **Functions that deviate from the C++ syntax like this one have specific documentation in Python.**
- Convert data type: `a = dip.Image((256, 256), dt='UINT8'); b = dip.Image(a, dt='UINT8')` fails.
    ➜ **Use `dip.Convert()` instead.**
- Advanced indexing: `a = dip.Image((256, 256)); a[0,[1, 3]]` fails, but `np.asarray(a)[0,[1, 3]]` works.
    ➜ **It's cheap to convert to NumPy array, for complex indexing like this. We're only supporting indexing as defined in C++ for now. We're open to changing this, but it won't be easy.**
- Tensor indexing: Maybe use `a(0)` instead of `a.TensorElement(0)`?
    ➜ **Done.**
- Tensor vs dimension when converting from numpy:
    ```python
    dip.Image(np.zeros((256, 256, 9)))  # Tensor image
    dip.Image(np.zeros((256, 256, 10))) # 3D image
    ```
    How to do this consistently?
    ➜ **Added an optional argument `axis` to this constructor, to allow the user to pick which dimension (if any) to use as the tensor dimension. The default behavior hasn't changed.**
- Passing empty images: `dip.Mean(a, dip.Image())`. Should be able to be written as `dip.Mean(a, ())`, `dip.Mean(a, [])`, or `dip.Mean(a, None)`?
    ➜ **Done. `None` casts implicitly to a raw (empty) `dip.Image`.**

Continue the discussion here: #105
