### ISSUE TITLE
CMake libics error

### ISSUE THREAD

**Issue by slokhorst** [DIPlib/diplib#30]
When running the `cmake` command, it gives the following error:

```
~~~Configuring libics~~~
CMake Error: File /home/sebas/Projects/diplib/dependencies/libics/cmake/libicsConfig.cmake.in does not exist.
CMake Error at /usr/share/cmake-3.14/Modules/CMakePackageConfigHelpers.cmake:330 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  dependencies/libics/support/cpp_interface/CMakeLists.txt:52 (configure_package_config_file)
  dependencies/libics/CMakeLists.txt:224 (include)
```
[cmake.log](https://github.com/DIPlib/diplib/files/3085178/cmake.log)

The file `libicsConfig.cmake.in` is included here, but it is missing from this repository: https://github.com/DIPlib/diplib/blob/c528265acad57a296c7a77b702e594f49e5baf8c/dependencies/libics/support/cpp_interface/CMakeLists.txt#L53

Using `cmake -DDIP_ENABLE_ICS=Off` works around the problem.

Using diplib c528265acad57a296c7a77b702e594f49e5baf8c with CMake 3.14.2 on Arch Linux.

**Comment by slokhorst** [comment]
This seems to be an error introduced in the latest commit. Rolling back to a3e347eaee5a387abe8d5141f8bc088b406273e3 removes the error.

**Comment by crisluengo** [comment]
Thanks for pointing this out! It looks like I need to clean my build directory before committing to master. :)
