### ISSUE TITLE
Watershed function maxSize parameter

### ISSUE THREAD

**Issue by pstack12** [DIPlib/diplib#37]
What are the units for the maxSize parameter? I assume pixels. My output doesn’t change regardless of what value I pass in for maxSize. Has anyone else had an issue with this?  Thanks.

**Comment by crisluengo** [comment]
Yes, `maxSize` is in pixels. `maxSize` works together with `maxDepth`, in that a region must be smaller or equal to both these thresholds to be merged. If you don't see an effect when changing the `maxSize` parameter, try increasing `maxDepth` first.

For example, using the image `cermet` that is in the `examples` directory, in MATLAB:
```matlab
a = readim('cermet');
watershed(a,1,50,100) % yields few large watershed regions
watershed(a,1,50,10)  % yields more, smaller watershed regions
watershed(a,1,50,1)   % yields many tiny watershed regions
```

Note that setting `maxSize=0` is equivalent to setting `maxSize` to infinity, meaning that only the depth of a region influences whether it will be merged or not.

See [the documentation](https://diplib.github.io/diplib-docs/group__segmentation.html#ga2b4d01c009b125f9d74bb8a1fc5d0cbf).
