### ISSUE TITLE
GLFW 3.3 error in Python 3.7 on Windows 10

### ISSUE THREAD

**Issue by ronligt** [DIPlib/diplib#43]
**Component**
GLFW 3.3

**Describe the bug**
After succesfull compilation with Visual Studio 2019 calling `dv.Show(img)` gives the following error in Python 3.7:

``` python
RuntimeError: Failed to create window
in function: createWindow (D:\src\diplib\viewer\src\manager\glfw.cpp at line number 70)
in function: Show (D:\src\diplib\viewer\src\dipviewer.cpp at line number 65)
```

Using FreeGLUT 3.0.0-2 instead of GLFW works fine!

**To Reproduce**

``` python
import PyDIP as dip
import PyDIP.PyDIPviewer as dv
fname='d:/images/acros.ics'
img=dip.ImageReadICS(fname)
dv.Show(img)
dv.Spin()
```

**System information:**
 - Windows 2016
 - Python 3.7
 - Visual Studio 2019

**Comment by wcaarls** [comment]
Hmm. I just did a test with GLFW 3.3 on Linux and it works. Since GLFW 3.3 adds the glfwGetError function to get an error string, I added that to the error message. Could you reproduce the error with the latest version and report what it says?

**Comment by ronligt** [comment]
Nice! That explained a lot:

```python
RuntimeError: Failed to create window: WGL: The driver does not appear to support OpenGL
in function: createWindow (D:\src\diplib\viewer\src\manager\glfw.cpp at line number 85)
in function: Show (D:\src\diplib\viewer\src\dipviewer.cpp at line number 65)
```

I'm compiling and building on a virtual server via Citrix Viewer. After testing the build **with** GLFW on a *real* computer all works fine.

Thanks for the help Wouter! :-)
