### ISSUE TITLE
Img show: don't show image 

### ISSUE THREAD

**Issue by clnFind** [DIPlib/diplib#45]
**Component**
PyDIP 

**Describe the bug**
  * run the following code,  image don't display,  process finished with exit code 0.
  ```
  import PyDIP as dip
  a = dip.ImageRead('./img/line_noisy.jpg')
  a.Show()
 ```
* I solve it,  as follow:
     * modify PyDIP_py.py file:  lines 151
       ```
        pp.show(block=Flase)  -->  pp.show(block=True) 
       ```

**Comment by crisluengo** [comment]
The documentation does say it's an experimental feature. Your crashing might be related to the version of Matplotlib used.

I just learned about pyplot's `draw()`. You can replace `pp.show(block=False)` with
```python
        pp.draw()
        pp.pause(0.001)
```
This seems to work just as well as the non-blocking `show()` for me. I will push this change to master.

**Comment by clnFind** [comment]
@crisluengo Thanks, it works.
