### ISSUE TITLE
Python examples in Jupyter Notebooks

### ISSUE THREAD

**Issue by Abhijit-2592** [DIPlib/diplib#5]
This is not an issue but a request!

A few Jupyter Notebooks explaining the use of python bindings will be useful for python users like me.

Thanks

**Comment by crisluengo** [comment]
I totally agree. Docstrings would be great to have too.

For now  [examples/pydip_examples.py](https://github.com/DIPlib/diplib/blob/master/examples/pydip_examples.py) and the [extensive DIPlib documentation](https://diplib.github.io/diplib-docs/) is all we have. I hope it can help you find out usage, and that the lack of documentation won't scare you away. 

The Python bindings are very rough still, it would be nice to rename the functions and objects to uses snake_case, add iterators and other convenience functions, etc. I'm not sure I know enough about Python to do a good job designing these, and I'm hoping someone enthusiastic enough will jump in and help to do that. :)

**Comment by Abhijit-2592** [comment]
@crisluengo This library is awesome! and I am certainly going to use this for my quantitative image analysis work. I will cook up a few jupyter notebooks as I learn and get accustomed with this library. I also found that this library can seamlessly integrate and work with OpenCV Skimage etc. Pull Request with example notebooks and images for working with PyDIP sounds good? 
Thanks :)

**Comment by crisluengo** [comment]
@Abhijit-2592 Yes, anything that you can contribute will be appreciated. Many thanks!

**Comment by crisluengo** [comment]
We have a start for this [here](https://github.com/DIPlib/diplib/blob/master/examples/pydip_examples.ipynb).

**Comment by crisluengo** [comment]
The file referenced above was moved, we have a few Jupyter Notebooks now: https://github.com/DIPlib/diplib/tree/master/examples/python
