### ISSUE TITLE
Moving diplib website to new implementation

### ISSUE THREAD

**Issue by ronligt** [DIPlib/diplib#52]
The current diplib website https://www.diplib.org still contains information about the "old" release of DIP*lib*/DIP*image* versions 1 and 2.

The moment diplib version 3 goes out of beta and into production the website will be redirected to the website of version 3 https://diplib.github.io/. Also this website will be updated to reflect these changes.

The following actions will be taken:

- [x] update https://diplib.github.io
  - no more support and maintenance for version 1 and 2
  - future mails to [bugs@diplib.org](mailto:bugs@diplib.org) will be redirected to [Issues](https://github.com/DIPlib/diplib/issues)
  - include link to FTP site with old binaries (version 1 and 2): ftp://qiftp.tudelft.nl/DIPimage/
  - more comics!
- [ ] send mail to old maillist of DIP*lib* version 2 about migration
- [x] redirect https://www.diplib.org to new site
- [ ] cleanup diplib.org domain at Google and delete site
- [ ] move domain to TU Delft

**Comment by crisluengo** [comment]
@ronligt You decided against moving the domain away from GSuite because of the email, right?

Can this issue be closed then?

**Comment by ronligt** [comment]
@crisluengo That's right.

I will have to send an e-mail to the old maillist of Dip*lib* version 2. And possibly clean up GSuite...

Still the matter of redirecting bugs@diplib.org to https://github.com/DIPlib/diplib/issues. Actually this might not be a good idea. I prefer receiving the e-mail and if appropriate create an Issue myself.
