### ISSUE TITLE
Cannot start DIPimage GUI in Matlab R2020a

### ISSUE THREAD

**Issue by fatcatZF** [DIPlib/diplib#56]
I encountered some errors when I tried to start DIPImage GUI in Matlab R2020a
![Screen Shot 2020-05-10 at 11 38 02 AM](https://user-images.githubusercontent.com/60744933/81496240-9afa0080-92b6-11ea-81dd-2a297954525f.png)

**Comment by crisluengo** [comment]
@fatcatZF How did you install the toolbox? What operating system are you using?

It seems that at least one MEX-file is missing. This indicates an incomplete installation.
