### ISSUE TITLE
PyDIP, building wheels and distribution on PyPI

### ISSUE THREAD

**Issue by wcaarls** [DIPlib/diplib#58]
It would be nice if PyDIP could be installed from pip. In order to do that, we need to build installation packages and upload them to PyPI. These do not need to be compiled by the user -- we can distribute binaries, although we need to provide these for all platforms and all Python versions (see, for example, the [Tensorflow](https://pypi.org/project/tensorflow/#files) project).

Questions:
- Source or binary?
- If binary, where should it be compiled? By us/@ronligt locally? Or automatically on Travis? Which Python versions?
- When cloning from github, should we build a wheel and install it, or keep it as is? Note that the requirements are different: a github build should not place the dynamic libraries in the package directory, while a binary wheel should.

I'm leaning towards binary wheels compiled on Travis for Python 3.6-3.8, with the local install also done through a binary wheel (but without the dynamic libraries). Of course, *how* to do this is a different kettle of fish...

**Comment by crisluengo** [comment]
That would be great. I think a binary distribution would make things a lot simpler for the end user. Especially on Windows and MacOS, where a compiler is not installed by default.

If we can make the binary releases through Travis, it would reduce the workload for @ronligt significantly, which is a good thing. We'd be able to make releases much more frequently.

One problem with distribution through PyPI is that there's already a package called [pydip](https://pypi.org/project/pydip/), and PyPI is not case sensitive. So we'd have to rename the package. Maybe just call it "diplib"?

**Comment by crisluengo** [comment]
This is looking really good! I made a few more changes to the text in INSTALL.md, and updated the Python examples for the new import statement.

Regarding the new import statement: Should we keep referring to the Python bindings as PyDIP if that's not the name of the package being imported?

When you `pip install opencv-python`, you then do `import cv2`. How do they change the name of the package? It is a bit confusing though to have two different names there, I don't think we should imitate that.

So yes, feel free to push this to master.

**Comment by wcaarls** [comment]
Merged. Windows wheels (created locally) for the current master branch are now available at https://test.pypi.org/project/diplib/, installable as

```
python -m pip install -i https://test.pypi.org/simple/ diplib
```

**However** it still requires users to install the Visual Studio 2019 redistributable package, and lots of testing in different environments.

@crisluengo I suggest you create a PyPI account and send me a token for uploads.

Regarding the naming, it is indeed confusing, but changing every PyDIP reference to "the diplib Python bindings" is a mouthful. I'm pretty sure naming both the module and package `diplib` is the right way to go, though (they can be different).

**Comment by wcaarls** [comment]
manylinux2010 wheels added to the testpypi repository. I had to use manylinux2010 because the manylinux1 compiler does not support generic lambdas. Additionally, auditwheel included some extra libraries in the distribution:

- `libXxf86vm` and `libXi`:  MIT license
- `libglut` (from freeglut): X consortium license
- `libgomp`: GPL with Runtime Exception

The last one should be investigated.

NOTE: the default pip on Ubuntu is very old and does not support manylinux2010. You first need to upgrade pip itself before installing diplib.

```bash
sudo apt install python3-pip python3.7
python3.7 -m pip install pip
python3.7 -m pip install -i https://test.pypi.org/simple/ diplib
```

All done locally for now, no Travis.

**Comment by crisluengo** [comment]
This is wonderful!

I'm sure all the binary distributions also carry the C and C++ libraries, and whatnot. It's hard to know what gets included and what doesn't. libgomp I guess carries the same licensing as the other GCC runtime libraries and header files. I tried to find information about this, but it's all second-hand. The libgomp website and documentation don't mention the exception at all.

FreeGLUT is already mentioned in the README.md file.

**Comment by wcaarls** [comment]
It's here:

https://github.com/gcc-mirror/gcc/blob/master/libgomp/libgomp.h

so I guess it's ok.

**Comment by wcaarls** [comment]
I added PyDIPjavaio to the distributable wheels. Of course, that doesn't work without Bio-Formats, so I added an option to download it through

```
python3.7 -m diplib download_bioformats
```

**Comment by crisluengo** [comment]
I can build wheels on macOS now. I have two external libraries that I want to include:
 - `/usr/local/Cellar/glfw/3.3.2/lib/libglfw.3.3.dylib`
 - `/usr/local/Cellar/libomp/10.0.0/lib/libomp.dylib`
I've found `delocate`, which is the macOS version of `auditwheel`. But it will copy in also `libjvm.dylib`, which we don't want to do. This tool doesn't seem to offer a way to exclude a library.

I'm thinking of making a wheel that doesn't include DIPjavaio, just to have something out there for macOS.

**Comment by wcaarls** [comment]
We could monkey-patch `delocating.filter_system_libs`. Auditwheel also doesn’t support it, but I hacked it in...

**Comment by crisluengo** [comment]
Indeed, it seems pretty straight-forward to copy the `delocate_wheel.py` script and add an appropriate `copy_filt_func` to the `delocate_wheel` call: https://github.com/matthew-brett/delocate/issues/77#issuecomment-644429498

**Comment by wcaarls** [comment]
I suggest something along the lines of 

```python
import sys, re
from delocate.cmd.delocate_wheel import main
import delocate.delocating

def filter_system_libs(libname):
   return not (libname.startswith('/usr/lib') or
               libname.startswith('/System') or
               libname.find('libjvm.dylib') >= 0)

def delocate_wheel(in_wheel,
                   out_wheel = None,
                   lib_sdir = '.dylibs',
                   lib_filt_func = None,
                   copy_filt_func = filter_system_libs,
                   require_archs = None,
                   check_verbose = False,
                  ):
    return delocate.delocating.delocate_wheel(in_wheel, out_wheel, lib_sdir, lib_filt_func, copy_filt_fu                             nc, require_archs, check_verbose)

delocate.cmd.delocate_wheel.delocate_wheel = delocate_wheel

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

**Comment by crisluengo** [comment]
Leaving this link here for future reference: instructions to get Travis to upload wheels to PyPI. It's possible to have it only do this if there's a tag present.
https://docs.travis-ci.com/user/deployment/pypi/#upload-artifacts-only-once

**Comment by wcaarls** [comment]
I like that. Linux wheels are now uploaded to PyPI upon tagging. For Windows, I'm still trying to figure out how to install more than one Python version at the same time. Probably in different installation directories. MacOS should be reasonably straightforward with your script.

**Comment by wcaarls** [comment]
Automatic deployment now works for all platforms.

@crisluengo It seems the MacOS build is not using multithreading:

```
-- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES) 
-- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES) 
-- Could NOT find OpenMP (missing: OpenMP_C_FOUND OpenMP_CXX_FOUND) 
```

even though the deployment build does not use `-DDIP_ENABLE_MULTITHREADING=Off`, and libomp is installed. Could you have a look?

**Comment by crisluengo** [comment]
I still see `-DDIP_ENABLE_MULTITHREADING=Off` in the macOS section of the `.travis.yml` file. https://github.com/DIPlib/diplib/blob/120ac8f7e96ba2248b793f8b3125d3c1116dcee5/.travis.yml#L21
I guess the deployment build runs in the same `build` directory as the verification build, and so the `cmake` command only updates existing configuration options.

**Comment by crisluengo** [comment]
By the way, how does that encrypted token work? Can I not take that and put it in a different Travis configuration for a different project and upload that project as "diplib"?
Maybe the repo URL is baked into the encoded token, so it only works for one project?
Just curious...

**Comment by crisluengo** [comment]
(oops, wrong button!)

**Comment by wcaarls** [comment]
I'm not sure. Maybe. Theoretically the build is cleaned before deployment. But it can't even find OpenMP?

The secret is encrypted with a project-dependent public key. The private key is known only to Travis.

**Comment by crisluengo** [comment]
Updating Xcode to 11.0 did the trick:
```none
-- Found OpenMP_C: -Xclang -fopenmp (found version "3.1") 
-- Found OpenMP_CXX: -Xclang -fopenmp (found version "3.1") 
-- Found OpenMP: TRUE (found version "3.1")  
```
This updated both the compiler and CMake, not sure which was the problem.

The `brew` command first updates Homebrew, and took 270s for the 10.3 image and 150s for the 11.0 image. So annoying having to wait on that! Also, that's a long time for something unnecessary. Their image should have updated software installed, to avoid repeatedly doing this sort of thing. Imagine all the projects running macOS tests, each of those tests spends 3-5 minutes doing exactly the same thing... Wow!

**Comment by wcaarls** [comment]
Yes, I tried HOMEBREW_NO_AUTO_UPDATE=1 but it didn’t work...

**Comment by wcaarls** [comment]
Seems to work! Is anything else needed before we can close this?

**Comment by crisluengo** [comment]
Awesome!
I guess all that is left is merging into master.
Thank you sir for getting all this to work!

**Comment by wcaarls** [comment]
My pleasure!
