### ISSUE TITLE
Accessing codes from ChainCode

### ISSUE THREAD

**Issue by acycliq** [DIPlib/diplib#62]
**Component**
PyDIP: 3.0b7

**Describe the bug**
Not quite sure if I am missing something trivial here but shouldnt  `ChainCode` expose  `codes` ? This is how I trying to do it 

**To Reproduce**
```
import numpy as np
import diplib as dip

import numpy as np
import diplib as dip
img = np.identity(3, dtype=np.uint8)
cc = dip.GetImageChainCodes(img)
for c in cc:
    print('Object ID: %s' % c.objectID)
    print('is 8 connected: %s' % c.is8connected)
    print('Starting pixel: %s' % (c.start,))
    print(c.codes)
```
 This is what the code above returns:

```
Object ID: 1
is 8 connected: True
Starting pixel: (0, 0)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-26-79151bde5160> in <module>
      7     print('is 8 connected: %s' % c.is8connected)
      8     print('Starting pixel: %s' % (c.start,))
----> 9     print(c.codes)

AttributeError: 'diplib.PyDIP_bin.ChainCode' object has no attribute 'codes'

```

**System information:**
I am running Windows 10, Python 3.7, numpy 1.18.5

**Comment by crisluengo** [comment]
Yes, it looks like we never exposed the data in the chain code in the Python interface. Wow, what a silly omission!

**Comment by acycliq** [comment]
Is a new release required please? I am still getting the same error and pip still installs version 3.0b7

**Comment by crisluengo** [comment]
@acycliq OK, I've started a release build. It will be at 3.0b8 when it's done.
https://travis-ci.org/github/DIPlib/diplib/builds/739724809
