### ISSUE TITLE
MacOS Catalina 10.15.17 

### ISSUE THREAD

**Issue by olasabet** [DIPlib/diplib#64]
I just update my MacOS operating system to MacOS Catalina 10.15.17
 - Upon initializing MATLAB (2018b), I got the following message
 - "dip_initialise.mexmaci64" cannot be opened because the developer cannot be verified. 
 - Then i have two options (Move to Bin (which doesn't work) or Cancel) and if I cancel to start MATLAB anyway I get the following:
  
Initialisation of DIPlib failed. The most probable cause is incorrect
   installation. Please make sure that the DIPimage distribution you    
   have is compatible with your operating system, architecture and/or   
   MATLAB version. What follows is a diagnostic tool that should help   
   debugging your installation:                                         
 
   The files libdip.dylib, libdipio.dylib and libdml_mlv8_2.dylib must be available
   on the library search path. Looking for them now:
     Scanning 
 
   Summary of Library locations:
     libdip.dylib not found
     libdipio.dylib  not found
     libdml_mlv8_2.dylib not found
     /Applications/dip/common/mlv8_2/diplib/private/dip__initialise.mexmaci64 (16-Oct-2017 07:56:28)
 
   Some or all of the relevant libraries were not found.
 
   Please read the manual for more information on installing this       
   toolbox. It can be found at:                                         
   http://www.diplib.org/documentation/dipimage_user_manual.pdf         
 
 
Warning: Executing startup failed in matlabrc.
This indicates a potentially serious problem in your MATLAB setup, which should
be resolved as soon as possible.  Error detected was:

Initialisation of DIPlib failed. 
>>

**Comment by crisluengo** [comment]
Apple keeps increasing security, which is a good thing. The binaries you're trying to install haven't been signed, and so are not allowed to run on your system.

You should be able to tell your system that it's OK to run these binaries by following the instructions in [this page](https://support.apple.com/en-gb/HT202491), towards the bottom under the header "How to open an app that hasn’t been notarised or is from an unidentified developer".

**Comment by crisluengo** [comment]
Here's I think an easier solution. Run this on the command line (⌘-space, then type "terminal" and run the "Terminal.app" program):
```bash
spctl --add --label "DIPlib" --path /Applications/dip/common/mlv8_2/diplib/private/*
spctl --add --label "DIPlib" --path /Applications/dip/common/mlv8_2/diplib/*
spctl --add --label "DIPlib" --path /Applications/dip/common/mlv8_2/dipimage_mex/private/*
spctl --add --label "DIPlib" --path /Applications/dip/common/mlv8_2/dipimage_mex/*
spctl --add --label "DIPlib" --path /Applications/dip/Darwin/lib/*
```
You will be prompted for your admin password. If I understood it correctly, this will add all the DIPimage binaries to the list of allowed programs.

Please report back letting us know if this worked or not!

[*For future visitors: you might need to adjust the `/Applications/dip` part of the path if you installed DIPimage in a different place, or the `mlv8_2` part of the path if you have a version of DIPimage built for a different version of MATLAB.*]

**Comment by olasabet** [comment]
So I started with second solution, it didn't work. I then followed the apple instructions in the link you shared and now it is working. Thanks a lot!

**Comment by crisluengo** [comment]
@olasabet Awesome! Thank you!

I was worried that that first approach would require approving each of the MEX-files individually, which would be quite annoying...
