### ISSUE TITLE
numberofthreads error

### ISSUE THREAD

**Issue by ThijmenL98** [DIPlib/diplib#65]
**Component**
Select one or more of: DIPimage
latest

**Describe the bug**
MatLab DIPImage error after a clean install

**To Reproduce**
Install latest DIPImage to a fresh MatLab R2020b install.

**System information:**
 - What OS do you have? Windows 10
 - If DIPimage, what version of MATLAB do you have? R2020b

![screenshot of console](https://user-images.githubusercontent.com/4462912/110210161-b6ab4480-7e90-11eb-8884-c6c15e527afa.png)

**Comment by crisluengo** [comment]
Thijmen,

You should have a file `C:\Program Files\MATLAB\R2020b\toolbox\dip\dipimage\private\numberofthreads.mexw64`. Can you find this file? If so, open it with the [Dependency Walker](https://www.dependencywalker.com) program. This should tell us what dependencies are missing.

Did you build the toolbox yourself from source, or did you install the binary release from the file `DIPlib3_installer_2018b.exe`? If the latter, did you also install the [Visual C++ Redistributable for Visual Studio 2019](https://aka.ms/vs/16/release/VC_redist.x64.exe)?

**Comment by ThijmenL98** [comment]
No such file existed, I reverted to using the installer, which seemed to work better. Is it correct that the 6+ images opened by dipinit are all black?

**Comment by crisluengo** [comment]
Yes, dipinit opens a bunch of display windows that will be used when you display images later. You don’t need to use dipinit, or you can customize it as you please. See the [User Manual](https://diplib.org/diplib-docs/sec_dum_customizing.html#sec_dum_customizing_dipinit).
