### ISSUE TITLE
Tensor multiplication issue in DipImage3.0 compared to 2.9

### ISSUE THREAD

**Issue by bscott711** [DIPlib/diplib#69]
**Component**
Select one or more of: DIPimage 
Include the release version: DIPimage 2.9 installer win64 (working) DIPlib3_installer_2018b (Issue)

**Describe the bug**
A clear and concise description of what the bug is. Include a description of observed results and expected results.

**To Reproduce**
[test_data.zip](https://github.com/DIPlib/diplib/files/6430658/test_data.zip)

Dip 2.9
d = newimar(3,1);
d{1} = readtimeseries('gg.tif');
d{2} = readtimeseries('gr.tif');
d{3} = readtimeseries('rr.tif');
B =[0.5639,0.0000,-0.5636;
0.0317,0.0036,2.1736;
0.0018,0.9867,0.1268;]
c = inv(B) * d

Dip 3
gg = readtimeseries('gg.tif');
gr = readtimeseries('gr.tif');
rr = readtimeseries('rr.tif');
d = newtensorim(gg,gr,rr);
B =[0.5639,0.0000,-0.5636;
0.0317,0.0036,2.1736;
0.0018,0.9867,0.1268;]
c = inv(B) * d

# c will be a new (3,1) tensor if working.
DipImage 2.9 -> Output as expected.
DipImage 3.0 -> Error using dip_operators.

Error using dip_operators
Log:
Sizes don't match
in function: SingletonExpandedSize (D:\src\diplib\src\library\framework.cpp at line number 40)
in function: Scan (D:\src\diplib\src\library\framework_scan.cpp at line number 141)
in function: MultiplySampleWise (D:\src\diplib\src\math\arithmetic.cpp at line number 365)
in function: Multiply (D:\src\diplib\src\math\arithmetic.cpp at line number 279)

Error in  *  (line 1725)
         out = dip_operators('*',lhs,rhs,dipgetpref('KeepDataType'));

**System information:**
 - What OS do you have? Windows 10
 - If DIPimage, what version of MATLAB do you have?
 - MATLAB Version: 9.6.0.1214997 (R2019a) Update 6
Operating System: Microsoft Windows 10 Education Version 10.0 (Build 19042)
Java Version: Java 1.8.0_181-b13 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode

**Comment by crisluengo** [comment]
As a workaround, you should be able to do this:
```matlab
invB = inv(B);
c = dip_image(invB(:),[3,3]) * d
```
