### ISSUE TITLE
Most classes in Measurement Modules are missing in PyDIP

### ISSUE THREAD

**Issue by Abhijit-2592** [DIPlib/diplib#7]
I am trying to measure Lines and Distance between Lines using this Library. In reference to the official documentation, classes such as ChainCode, ConvexHull, RadiusValues etc are missing in PyDIP module. I am able to access only PyDIP.MeasurementTool(). Unable to access PyDIP.ChainCode, PyDIP.ConvexHull  etc. Are there problems with my installation or those modules are not exposed to python? Kindly advice! Thanks

**Comment by crisluengo** [comment]
Those are not (yet?) exposed in the Python binding. What would you use them for?

**Comment by Abhijit-2592** [comment]
@crisluengo.  Kindly see the following images:
Component-1
![sww](https://user-images.githubusercontent.com/29851832/38159419-fc02b620-34c5-11e8-884b-032150ff199f.png)

Component-2
![thrust_piece](https://user-images.githubusercontent.com/29851832/38159420-035f5e32-34c6-11e8-9606-b87f35ac2d76.png)

The Images are roughly centered. There is still a large possibility to improve the imaging quality. 

In Component-1: 
I am Trying to Measure the Length and Thickness of the Component

In Component-2:
I am trying to Measure the distance between the 2 Flat edges and also the radius of curvature of the component. 

For Both of the above causes, My first Trivial Solution using OpenCV (Before finding this library) was:

1. Extract Edge Pixels using Canny
2. Find Contours
3. Fit a minimum bounding rectangle to it. 

This however does not give high accuracy or high precision. 

While I was searching for better methods I found [this](http://www.crisluengo.net/index.php/archives/310#more-310) post in your blog. I thought I would Implement it and see so that I get first hand experience of what's happening. Since I am more comfortable in python I tried to implement this using PyDIP. But unfortunately the ChainCode class is absent in PyDIP.

PS:
1. I measured the Diameter with the answer you gave on stackoverflow, Instead of using Area to calculate,  directly used the Mean Radius Returned by the MeasurementTool.Measure(..., 'Radius') And got a precision of 0.007mm with the same data. Thanks!
2. I am still working on measuring edge distances using this library. Will be grateful for any suggestions

I am just starting out with high precision quantitative analysis and looking for opportunities to Lean about the subject :)

**Comment by crisluengo** [comment]
The width and length of an object you can measure with the "Feret" feature. But these take the width of the projections, so there is a bias there: it will find the two pixels in either side of the object that are farthest away from each other as the width, rather than finding the average distance between opposite sides.

Ideally you'd take columns of pixels, and measure the distance there, and take the average. That's a little bit more involved, but could be done without the chain code stuff.

For the second object you probably do want to obtain a polygonal representation to compute curvature. There are other methods that compute curvature directly in greyvalue images, and probably lead to more precise results, but this is also not yet in the master branch. If you follow the 'erik' branch, dip.StructureTensorAnalysis should have a "curvature" option that computes curvature at every pixel. Make sure that the sigmas you use to compute the structure tensor are small, maybe 1 for the gradient and 1 or 2 for the smoothing. The larger the sigmas, the larger the bias. I can try proving more detail tonight or tomorrow night.

**Comment by Abhijit-2592** [comment]
Thanks for sharing your knowledge sir, I will try implementing it and will get back to you

**Comment by crisluengo** [comment]
This is more or less what I had in mind for the first one. Note how the minimum Feret diameter gives 789.8 pixels, but the more refined approach 785.7. Those few pixels difference is the bias you get from the Feret diameter taking the maximum width, not the average width.

```python
import PyDIP as dip
import math
import numpy as np
# Read
img = dip.ImageReadTIFF('/Users/cris/Downloads/machined_piece.tif')
img = img.TensorElement(1) # green channel
# Binarize
bin = ~dip.Threshold(img)[0]
bin = dip.EdgeObjectsRemove(bin)
bin = dip.AreaOpening(bin,filterSize=50) # remove noise
# Get Feret feature
msr = dip.MeasurementTool.Measure(dip.Label(bin),img,['Feret'])
print(msr)
# Rotate to align with horizontal axis
angle = msr[1]['Feret'][4] - math.pi/2
img = dip.Rotation2D(img,-angle)
# Binarize again
bin = ~dip.Threshold(img)[0]
bin = dip.EdgeObjectsRemove(bin)
bin = dip.AreaOpening(bin,filterSize=50) # remove noise
# Get bounding box
msr = dip.MeasurementTool.Measure(dip.Label(bin),img,['Minimum','Maximum'])
print(msr)
start = int(msr[1]['Minimum'][0]) + 100
stop = int(msr[1]['Maximum'][0]) - 100
width = 0
for ii in range(start, stop):
   line = bin[ii,:].Squeeze()
   width += np.diff(np.nonzero(line)[0][[0,-1]])[0]
width /= (stop-start+1)
print(width)
```

I'm not yet sure about the curvature. I'll try to bind the chain code and polygon classes to Python this week.

**Comment by Abhijit-2592** [comment]
Thanks sir, I have been working on a method from your recommendation too. Will get back to you in another day after I complete it.

**Comment by crisluengo** [comment]
That sounds like a really good approach.

**Comment by Abhijit-2592** [comment]
My code for the First Image
I haven't fitted the Line using RANSAC and measured the normal distance because, for 2 lines the min distance or normal distance is defined only when the two lines are parallel. Theoretically, the two lines are parallel But, The fitted lines need not be. What is your opinion on the below approach?

**This method is very specific for component_1**

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
@author: abhijit
"""

import cv2
import numpy as np
import PyDIP as dip

#Custom Modules: See the bottom of the file for the main script
def Euclidian_distance(pt1_list,pt2_list):
    """
    Calculate the euclidian distance for 2 sets of points
    
    Keyword arguments
    pt1_list: --list : A list of points (x,y)
    pt2_list: --list : A list of points (x,y)
    
    Returns the list of distances
    
    """
    euclidian_d = lambda pt1,pt2: np.sqrt(np.square(pt1[0]-pt2[0]) + np.square(pt1[1]-pt2[1]))
    distances = []
    for a,b in zip(pt1_list,pt2_list):
        distances.append(euclidian_d(a,b))
    return(distances)

class Line_Edge_points:
    
    def __init__(self,edge_img,Range=50):
        """
        Finds the edge points
        Keyword Arguments:
        edge_img: np.array(): numpy array of edge image from canny or any other edge detection method
        Range: int: number of edge points to find (center-Range,center+Range) Default = 50
                    if Range is 50 it returns 100 points
        """
        assert len(edge_img.shape) == 2, "Image must be a binary edge image like output from canny"
        self.edge_img = edge_img
        self.Range = Range
        
    def get_points(self,centroid,direction,check_num=2,lead=0):
        """ Interface function to find Edge points in left,right,top,bottom of a given edge_image
        
        Keyword Arguments
        
        centroid --tuple: (x,y) center point of the edgeimage (x,y) not (r,c)
        direction --str: one of top, bottom, left, right
        check_num --int: similar to connectivity (if edge is found checks the next n pixels to make sure it is the edge) default 2
        lead --int: initial lead (in pixels) for faster implementation default 0 (Care to be taken while giving the lead)
        
        Returns a list containing the edge points
        """
        assert direction in ['left','right','top','bottom'], 'Direction must be one of left, right, top, bottom'
            
        if direction == 'left':
            points = self._left_edges(centroid,check_num,lead)
        elif direction == 'right':
            points = self._right_edges(centroid,check_num,lead)
        elif direction == 'top':
            points = self._top_edges(centroid,check_num,lead)
        else:
            points = self._bottom_edges(centroid,check_num,lead)
            
        return points
            
        
        
    def _right_edges(self,start_point,check_num=2,lead=0):
        cx,cy = start_point
        right_points = []
        for i in range(cy-self.Range,cy+self.Range):
            right_points.append(self._right_edge(start_point=(cx+lead,i),check_num=check_num))
        return right_points
        
    def _left_edges(self,start_point,check_num=2,lead=0):
        cx,cy = start_point
        left_points = []
        for i in range(cy-self.Range,cy+self.Range):
            left_points.append(self._left_edge(start_point=(cx-lead,i),check_num=check_num))
        return left_points
        
    def _top_edges(self,start_point,check_num=2,lead=0):
        cx,cy = start_point
        top_points = []
        for i in range(cx-self.Range,cx+self.Range):
            top_points.append(self._top_edge(start_point=(i,cy-lead),check_num=check_num))
        return top_points
    
    def _bottom_edges(self,start_point,check_num=2,lead=0):
        cx,cy = start_point
        bottom_points = []
        for i in range(cx-self.Range,cx+self.Range):
            bottom_points.append(self._bottom_edge(start_point=(i,cy+lead),check_num=check_num))
        return bottom_points
    
    def _right_edge(self,start_point,check_num):
        c,r = start_point
        flag = False
        add_num = 1

        while True:
            if self.edge_img[r][c] == 255:
                flag = True
                for i in range(check_num):
                    if self.edge_img[r,c+add_num+i] ==255:
                        flag = False
                if flag:
                    pt_x = c
                    pt_y = r
                    return (pt_x,pt_y)
            else:
                c+=add_num
                
    def _left_edge(self,start_point,check_num):
        c,r = start_point
        flag = False
        add_num = -1

        while True:
            if self.edge_img[r][c] == 255:
                flag = True
                for i in range(check_num):
                    if self.edge_img[r,c+add_num-i] ==255:
                        flag = False
                if flag:
                    pt_x = c
                    pt_y = r
                    return(pt_x,pt_y)
            else:
                c+=add_num
                
    def _top_edge(self,start_point,check_num):
        c,r = start_point
        flag = False
        add_num = -1

        while True:
            if self.edge_img[r][c] == 255:
                flag = True
                for i in range(check_num):
                    if self.edge_img[r+add_num-i,c] ==255:
                        flag = False
                if flag:
                    pt_x = c
                    pt_y = r
                    return(pt_x,pt_y)
            else:
                r+=add_num
    
    def _bottom_edge(self,start_point,check_num):
        c,r = start_point
        flag = False
        add_num = +1

        while True:
            if self.edge_img[r][c] == 255:
                flag = True
                for i in range(check_num):
                    if self.edge_img[r+add_num+i,c] ==255:
                        flag = False
                if flag:
                    pt_x = c
                    pt_y = r
                    return(pt_x,pt_y)
            else:
                r+=add_num

############################################################################################
# Main code:
img = cv2.cvtColor(cv2.imread("./component_1.png"),cv2.COLOR_BGR2RGB)
gray = cv2.cvtColor(img,cv2.COLOR_RGB2GRAY)
dip_img = dip.Image(gray) # useful for subpixel detection

blurred = cv2.bilateralFilter(gray,9,91,91)
edges = cv2.Canny(blurred,100,200)

ret_img,contours,hirarchy=cv2.findContours(edges,cv2.RETR_LIST,cv2.CHAIN_APPROX_SIMPLE)
#extract the max contour
max_contour = max(contours,key=cv2.contourArea)
#Find center in integer precision. Center is just a reference need not be very accurate and precise
M = cv2.moments(max_contour)
cx = int(M['m10']/M['m00'])
cy = int(M['m01']/M['m00'])

# Find the edge points here top and bottom has 400 points and left and right have 100 points (Range = 200,50)
p = Line_Edge_points(edge_img=edges,Range=50)
q = Line_Edge_points(edge_img=edges,Range=200)
right_points = p.get_points(centroid=(cx,cy),direction='right',check_num=2,lead=800)
left_points = p.get_points(centroid=(cx,cy),direction='left',check_num=2,lead=800)
top_points = q.get_points(centroid=(cx,cy),direction='top',check_num=2,lead=350)
bottom_points = q.get_points(centroid=(cx,cy),direction='bottom',check_num=2,lead=350)

#subpixel Refinement
refined_top = []
refined_bot = []
for t,b in zip(top_points,bottom_points):
    refined_top.append(tuple(dip.SubpixelLocation(dip_img,t).coordinates))
    refined_bot.append(tuple(dip.SubpixelLocation(dip_img,b).coordinates))
    
refined_right = []
refined_left = []

for r,l in zip(right_points,left_points):
    refined_right.append(tuple(dip.SubpixelLocation(dip_img,r).coordinates))
    refined_left.append(tuple(dip.SubpixelLocation(dip_img,l).coordinates))
    
diameter_pixel = np.array(Euclidian_distance(top_points,bottom_points))
diameter_subpixel = np.array(Euclidian_distance(refined_top,refined_bot))
length_pixel = np.array(Euclidian_distance(left_points,right_points))
length_subpixel = np.array(Euclidian_distance(refined_left,refined_right))

print("The diameter in pixel level: {}".format(diameter_pixel.mean()))
print("The diameter in subpixel level: {}".format(diameter_subpixel.mean()))
print("The length in pixel level: {}".format(length_pixel.mean()))
print("The length in subpixel level: {}".format(length_subpixel.mean()))
```

> The diameter in pixel level: 788.4025
> The diameter in subpixel level: 786.2403860415235
> The length in pixel level: 1783.02
> The length in subpixel level: 1784.7594711709573


### Edges Visualised:
If Zoomed in you can see the detected edge points as red and blue lines
![vis_img](https://user-images.githubusercontent.com/29851832/38288532-02edf680-37ef-11e8-9dd0-fc4de97fd0c3.png)

## PS:

- I have to evaluate your method and this method with the true value of the component.
- Any other suggestions to improve detection accuracy?
- Sorry for the long code :)

Thanks

**Comment by crisluengo** [comment]
[`dip.SubpixelLocation`](https://diplib.github.io/diplib-docs/group__analysis.html#ga8e36ea81d3521f412fd7c06f1e335cca) looks for a local maximum (or minimum if you set `polarity="minimum"`). I'm not sure what it does in this case, but it's likely not refining the edge location. What the function does is fit a parabola (by default, there are other methods) to the 3x3 neighborhood of the input coordinate, and return the parameters for the maximum of that parabola. This would work if you use `dip.GradientMagnitude(gray)` as input. But the method could still shift the point along the line as well, not necessarily only perpendicular to it. I would consider keeping only the sub-pixel location along the relevant direction (horizontal for left and right edges, vertical for top and bottom edges).

Note that you should be able to input a Numpy array as image into any PyDIP function, in the same way that you can pass a `dip.Image` object into a Numpy function. You *shouldn't* need to explicitly cast with `dip.Image(gray)`.

**Comment by Abhijit-2592** [comment]
Mmm I don't quite understand why the method will not work for the edge pixels. Could you please elaborate? From the explanation you gave for the dip.SubpixelLocation, the method would look at the 3x3 neighbour and fit a parabola this should result in a subpixel edge detection right?

**Comment by crisluengo** [comment]
It fits a parabola and then looks for the maximum of that parabola. The edge is not at the maximum intensity, it's at the maximum of the intensity gradient.

**Comment by Abhijit-2592** [comment]
Thanks. Now I understand
