### ISSUE TITLE
PyDIPjavaio unavailable

### ISSUE THREAD

**Issue by ronligt** [DIPlib/diplib#74]
**Component**
diplib 3.0.0 (a.k.a. PyDIP) from https://pypi.org/project/diplib/

**Describe the bug**
After successfully following installation instructions the following message is returned after `import`:

```python
Python 3.9.5 (default, May 18 2021, 12:31:01)
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import diplib as dip
PyDIPjavaio unavailable:
dlopen(/Users/rligteringen/miniconda3/envs/diptest/lib/python3.9/site-packages/diplib/PyDIPjavaio.cpython-39-darwin.so, 2): Library not loaded: @rpath/libjvm.dylib
  Referenced from: /Users/rligteringen/miniconda3/envs/diptest/lib/python3.9/site-packages/diplib/libDIPjavaio.dylib
  Reason: image not found

load_jvm returned '/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/lib/server/libjvm.dylib'
```

Note that `diplib` can be used except for `PyDIPjavaio`:

```python
>>> dip.hasDIPjavaio
False
```

**To Reproduce**

In shell (*note: same warning is given as with `import`*):

```bash
$ conda create -n diptest pip
$ conda activate diptest
(diptest) $ pip install diplib
(diptest) $ python -m diplib download_bioformats
PyDIPjavaio unavailable:
dlopen(/Users/rligteringen/miniconda3/envs/diptest/lib/python3.9/site-packages/diplib/PyDIPjavaio.cpython-39-darwin.so, 2): Library not loaded: @rpath/libjvm.dylib
  Referenced from: /Users/rligteringen/miniconda3/envs/diptest/lib/python3.9/site-packages/diplib/libDIPjavaio.dylib
  Reason: image not found

load_jvm returned '/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/lib/server/libjvm.dylib'
Retrieving https://downloads.openmicroscopy.org/bio-formats/6.5.0/artifacts/bioformats_package.jar
(diptest) $ python
```

In Python:

```python
>>> import diplib as dip
```

**System information:**
 - macOS 11.3.1
 - Python 3.9.5 (via conda 4.10.1)

**Debug information**

Inside the `site-packages/diplib` directory the following files are found:

```bash
$ ls -1
DIPjavaio.jar
PyDIP_bin.cpython-39-darwin.so
PyDIP_py.py
PyDIPjavaio.cpython-39-darwin.so
PyDIPviewer.cpython-39-darwin.so
__init__.py
__main__.py
__pycache__
bioformats_package.jar
libDIP.dylib
libDIPjavaio.dylib
libDIPviewer.dylib
loadjvm.py
```

With `otool` the dependencies are checked:

```bash
$ otool -L PyDIPjavaio.cpython-39-darwin.so
PyDIPjavaio.cpython-39-darwin.so:
	@rpath/libDIPjavaio.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libDIP.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 800.7.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.0.0)
$ otool -L libDIPjavaio.dylib
libDIPjavaio.dylib:
	@rpath/libDIPjavaio.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libDIP.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libjvm.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 800.7.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.0.0)
```

With `mdfind` the following `libjvm.dylib` are found:

```bash
$ mdfind libjvm.dylib
/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/lib/server/libjvm.dylib
/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/server/libjvm.dylib
/Users/rligteringen/miniconda3/envs/diptest/lib/python3.9/site-packages/diplib/loadjvm.py
```

**Comment by crisluengo** [comment]
Travis build environments use the Oracle Java SDK. Maybe the libjvm.dylib that you use, from OpenJDK, is not compatible and therefore cannot be linked?

Could you try to install OracleJDK, and see if that helps?

If this turns out to be the root of the problem, then I don’t know how we can solve this. Two versions of the diplib package for macOS on PyPI?

**Comment by ronligt** [comment]
I installed OracleJDK but still get this message:

```python
>>> import diplib as dip
PyDIPjavaio unavailable:
dlopen(/Users/rligteringen/miniconda3/envs/diptest/lib/python3.9/site-packages/diplib/PyDIPjavaio.cpython-39-darwin.so, 2): Library not loaded: @rpath/libjvm.dylib
  Referenced from: /Users/rligteringen/miniconda3/envs/diptest/lib/python3.9/site-packages/diplib/libDIPjavaio.dylib
  Reason: image not found

load_jvm returned '/Library/Java/JavaVirtualMachines/jdk-16.0.1.jdk/Contents/Home/lib/server/libjvm.dylib'
```

The `load_jvm.py` script **did** find this new Java SDK:

```bash
$ /usr/libexec/java_home
/Library/Java/JavaVirtualMachines/jdk-16.0.1.jdk/Contents/Home
$ /usr/libexec/java_home -V
Matching Java Virtual Machines (3):
    16.0.1 (x86_64) "Oracle Corporation" - "Java SE 16.0.1" /Library/Java/JavaVirtualMachines/jdk-16.0.1.jdk/Contents/Home
    11.0.5 (x86_64) "AdoptOpenJDK" - "AdoptOpenJDK 11" /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home
    1.8.0_292 (x86_64) "AdoptOpenJDK" - "AdoptOpenJDK 8" /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home
/Library/Java/JavaVirtualMachines/jdk-16.0.1.jdk/Contents/Home
```

Setting `JAVA_HOME` is also not helping:

```bash
$ export JAVA_HOME=`/usr/libexec/java_home`
```

**Comment by wcaarls** [comment]
It appears the libjvm discovery is going well, but it is not actually loading the library. Try replacing load_jvm() in load_jvm.py with:

```
def load_jvm():
    for path in suggest_jvm_paths():
        for file in suggest_jvm_files():
            lib = os.path.join(path, file)

            if os.path.exists(lib):
                if is_win and ctypes.WinDLL(lib) != 0:
                    return lib
                if (is_linux or is_mac) and ctypes.CDLL(lib) != 0:
                    return lib
```

But it seems there might be a different problem, where javaio is compiled with the most recent Java target, which on Travis is now apparently Java 14. We need to add a 

set(CMAKE_JAVA_COMPILE_FLAGS -target 1.7 -source 1.7)

before the add_jar in javaio/CMakeLists.txt. I'll look at it later.

**Comment by crisluengo** [comment]
@ronligt Did Wouter's code fix it also when you use OpenJDK? It would be nice to know if Oracle JDK is a requirement or not.

**Comment by wcaarls** [comment]
The original code was from python-javabridge. I don't know why they did it that way. Can you check that it still works with different Python versions on MacOS?

Oracle JDK should not be a requirement, but I think Java >14 might required because of the way Travis is configured at the moment.  Setting source and target to 1.7 should fix that, but again it would be nice to check first.

**Comment by crisluengo** [comment]
@wcaarls The simplified `load_jvm()` works just fine for me as well.

I do have a new issue with javaio: When building, CMake finds the Java that comes with CLion (my IDE), which is at 15. But when I try to use it, it wants to use my system's Java, which is at 8.

This can be solved by adding `set(CMAKE_JAVA_COMPILE_FLAGS "-target" "1.8" "-source" "1.8")` to the CMake file fixes this (I figure we require Java version 1.8 in `find_package`, might as well set that version for source and target). This would also avoid the binaries deployed to PyPI requiring Java 14 or later. However, I do see a warning now at compile time:

> warning: [options] bootstrap class path not set in conjunction with -source 8

Not sure how important this is. Things seem to work under my system Java now.

**Comment by wcaarls** [comment]
I suggested 1.7 because that's what's used for viewslice in DIPimage. I think one will overwrite the other.

The warning has always been there fir viewslice -- it shouldn't be a problem.

**Comment by crisluengo** [comment]
Oh, I see this comment in the CMake script for DIPimage:
> MATLAB R2013b--R2017a use Java SDK 1.7, R2017b-- use SDK 1.8.

Should we then not move all Java components to 1.7? In particular this one:
```cmake
find_package(Java 1.8 COMPONENTS Development)
```

On the other hand, the Java tool in DIPimage is the DIPviewer Java bindings, not javaio. So the Java version used in javaio is unrelated to it.

**Comment by wcaarls** [comment]
Finding version 1.7 should be fine. I suggested using the same version for both, because I think CMAKE_JAVA_COMPILE_FLAGS is a global variable that affects all subprojects.

**Comment by crisluengo** [comment]
OK, setting that global variable in one spot only then.

I do see this now:
> warning: [options] source value 7 is obsolete and will be removed in a future release  
> warning: [options] target value 7 is obsolete and will be removed in a future release

I guess when that happens we have to remove support for some older MATLAB versions.

I'm wondering (I know so little about the JVM) if "target value 7" is removed from a future release, does it mean that that release won't be able to run JAR files targeting 1.7? Or is it just the building of these JAR files that will no longer be possible?

**Comment by wcaarls** [comment]
I know little more than you. Since it is a compiler warning, it could indeed be that newer JDK versions won't support targeting 1.7 but the JRE will still support executing the resulting class files. In any event, I agree with you that we can just move to 1.8 when this becomes problematic -- it should be supported for a long time still.

**Comment by ronligt** [comment]
> @ronligt Did Wouter's code fix it also when you use OpenJDK? It would be nice to know if Oracle JDK is a requirement or not.

Yes, this solution also works for OpenJDK. Tested with 1.8.0_292 and 11.0.5.

**Comment by ronligt** [comment]
> The original code was from python-javabridge. I don't know why they did it that way. Can you check that it still works with different Python versions on MacOS?

Yes, this solution also works for another Python version. Tested with Python 3.7.10.
