### ISSUE TITLE
Matlab crash after using 'noise' (poisson) on a simple test image

### ISSUE THREAD

**Issue by tmtenbrink** [DIPlib/diplib#83]
**Component**
DIPimage (DIPlib 3.0.0 release, https://github.com/DIPlib/diplib/releases/tag/3.0.0), compiled from source

**Describe the bug**
I am testing some Matlab code for Fourier Ring Correlation, but when attempting to use the ```noise``` function with ```'poisson'``` as ```noise_type``` on a simple test image, Matlab itself crashes. Guassian does seem to work, so it seems to be a specific problem with poisson. When the function is executed, Matlab freezes and Microsoft Visual C++ Runtime Library error window pops up, describing some additional details. It seems like an invalid mean is passed to the random poisson function. See the image below.

![Screenshot 2021-09-13 143149](https://user-images.githubusercontent.com/64082573/133084220-2cfd4768-e9bd-454b-a388-e50e6370983b.png)

The buttons are not clickable as Matlab crashes and exits after a few seconds.

**To Reproduce**
1. Create a simple test image ```a = (yy('corner'))*sin((xx('corner'))^2/300);```
2. Run the poisson noise function on it ```a1 = noise(a,'poisson',1); %shotnoise 1```

I also tested this by importing a TIFF image, which fails in the same way.

**System information:**
 - What OS do you have? Windows 10
 - If DIPimage, what version of MATLAB do you have? MATLAB Version: 9.10.0.1739362 (R2021a) Update 5
 - If compiled from sources, what compiler and version did you use? I used CMake 3.21.2 with Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29915 for x64 (Microsoft Visual Studio 16 2019)

**Comment by crisluengo** [comment]
Poisson noise is added by generating, for each pixel, a Poisson-distributed random value with that pixel's value as mean. A Poisson random value must have a positive mean.

The C++ Poisson generator that comes with my compiler works just fine with non-positive mean, generating 0 as output. But there is an `assert` in some C++ standard libraries that verifies that the mean is not <=0. When building DIPlib/DIPimage in a release build, the assert is ignored, and things work just fine. It is explicitly the debug build that will error out this way. I have fixed DIPlib to call the C++ Poisson generator only if the input pixel is > 0.

Thanks for your report!

**Comment by tmtenbrink** [comment]
Ah, I was unaware the pixels could have negative values, I had assumed they would be nonnegative. Thank you for the information! 

One question: you say this should not happen in a release build, but isn't the 3.0.0 version a release build? Or must I have compiled it incorrectly from source?

**Comment by crisluengo** [comment]
@tmtenbrink  You triggered an assert, which are typically disabled in release builds, and active only in debug builds. In MSVC, ensure that you select "release" for build mode. I have very little experience with MSVC (or anything Windows), so I don't remember exactly what these build modes are called there, or what the default build mode is. But I'm fairly sure you build in debug mode.

In C++ there is an `assert` statement, which is turned on in debug mode and turned off in release mode. There is also the `DIP_ASSERT` macro, which we use in the DIPlib and DIPimage code. This one is turned on or off using a setting in CMake. It was an `assert` statement that was triggered, not a `DIP_ASSERT` macro.
