### ISSUE TITLE
PyDIP error when freeglut3 is not installed on Linux

### ISSUE THREAD

**Issue by tmtenbrink** [DIPlib/diplib#84]
**Component**
PyDIP 3.0.0

**Describe the bug**
When "freeglut3" is not installed on Linux, importing diplib (PyDIP) fails with the following error:
```
Traceback (most recent call last):
  File "/home/tmtenbrink/Files/Local projects/venv39/diptest.py", line 1, in <module>
    import diplib as dip
  File "/home/tmtenbrink/Files/Local projects/venv39/venv/lib/python3.9/site-packages/diplib/__init__.py", line 48, in <module>
    from . import PyDIPviewer as viewer
ImportError: libglut.so.3: cannot open shared object file: No such file or directory
```
Some investigation eventually led me to the installation of freeglut3, which solved the issue. My suggestion is to maybe add some check and/or documentation for this, so users know they have to install this library. My apologies if I missed it somewhere, but I couldn't find it on the PyPI, which is probably the best place to put it. On Windows I did not have any similar issue, everything works out of the box there.

**To Reproduce**
Use Ubuntu 21.04 (or some other Linux that doesn't come pre-installed with freeglut), install the most recent version of Python and install diplib. Then
```
import diplib
```
will cause it to fail if freeglut3 is not installed.

**System information:**
 - What OS do you have? Pop!_OS (Ubuntu 21.04)
 - If PyDIP, what version of Python do you have? 3.9.5

**Comment by crisluengo** [comment]
Thank you. Something neither of us noticed.

I've added a statement to the README file used in PyPI. But it would be nice to have this automatically installed. Not sure how to do this, or if it's even possible.

Can anyone with experience in PyPI help with this?

**Comment by wcaarls** [comment]
Theoretically libglut.so is shipped in the wheel, but apparently something is going wrong. I'm installing a fresh Ubuntu 21.04 VM to check.

**Comment by wcaarls** [comment]
Although the library is shipped in the wheel, auditwheel did not correctly replace the dependency of libDIPviewer.so to the new unique name generated for libglut.so.3. As such, it will not find it in diplib.libs, and crash if it is not available elsewhere.

This can be solved locally by either
1) Installing freeglut3
2) Renaming diplib.libs/libglut-f50f2fdc.so.3.9.0 to diplib.libs/libglut.so.3
3) Running patchelf --replace-needed libglut.so.3 libglut-f50f2fdc.so.3.9.0 libDIPviewer.so

But we need to figure out how to solve this for future distributions. Maybe it's a bug that was fixed in auditwheel already.

**Comment by wcaarls** [comment]
auditwheel 4.0.0 solved the problem, but was a bit more picky about other things. Now the generated wheel looks good, but it still requires testing.

**Comment by wcaarls** [comment]
I tested this on a fresh Ubuntu 21.04 setup with Python 3.9, and my old Ubuntu 18.04 system with Linux 3.6. It seems to work. What should we do? Release a patched 3.0.0 (3.0.1), or wait for 3.1.0?

**Comment by crisluengo** [comment]
Thank you @wcaarls !

If we make a release, it should be 3.1.0, there are some significant additions to the API that warrant that.

But Travis is not building our stuff any more, we’re out of build minutes. I’d like to move us to GutHub Actions, but haven’t started that work yet. So we cannot really make a release right now, unless we do that manually.

**Comment by crisluengo** [comment]
There’s a new release on PyPI, and it looks like freeglut3 is properly packaged.
