### ISSUE TITLE
dip::Polygon::CovarianceMatrix alternative

### ISSUE THREAD

**Issue by elgw** [DIPlib/diplib#87]
The dip::Polygon::CovarianceMatrix "Returns the covariance matrix for the vertices of the polygon". Is that really what the users would expect it to do?

Consider three representations of a square:
```
P = [[0, 0], [1, 0], [1, 1], [0, 1]]
dip::Polygon::CovarianceMatrix() = [0.25, 0; 0, 0.25]
P = [[0, 0], [0.2, 0], [1, 0], [1, 1], [0, 1]]
dip::Polygon::CovarianceMatrix() = [0.218, 0.03; 0.03, 0.25]
P = [[0, 0], [0.4, 0], [1, 0], [1, 1], [0, 1]]
dip::Polygon::CovarianceMatrix() = [0.202, 0.01; 0.01, 0.25]
```
The geometrical shape is the same but the covariance matrix different.

If a polygon is interpreted as a flat surface with uniform density, the result should be [1/12, 0; 0, 1/12] in all cases. Then the covariance matrix would be in agreement with the [covariance matrix calculated from binary objects](https://en.wikipedia.org/wiki/Image_moment). Possibly both alternatives could co-exist in the library.

Calculations can be done efficiently via Green's formula as an integral over the edges of the polygon. The drawback is that the polygons need to be _simple_ which can be verified (limited by numerical precision).  

 If this feature is of interest to DIPlib I could provide C-code or try to make a pull request.

**Comment by crisluengo** [comment]
I needed this, so I implemented it. 795f602d24478da9fd5e1f4eae16ddeb70717d7d

**Comment by elgw** [comment]
Great! I thought that you would need it :) Hope to do a little more of the work next time.
