### ISSUE TITLE
Rotation2D  Doesn't preserve the size of the image.

### ISSUE THREAD

**Issue by Abhijit-2592** [DIPlib/diplib#9]
The Rotation2D increases the spatial dimensions of the image. Which is not desirable

**Comment by crisluengo** [comment]
Preserving the size of the image would mean to cut off data, which is not always wanted. We err on the side of caution. You can crop the result like so:

    sz = img.Sizes()
    img = dip.Rotation2D(img, 0.2)
    img = img.Cropped(sz)

(In the C++ library there is also a `Crop()` method, which modifies the object directly. It hasn't been exported to Python, I'll look into doing that.)
