### ISSUE TITLE
Python 3.10 wheels

### ISSUE THREAD

**Issue by tmtenbrink** [DIPlib/diplib#93]
Hi!

I have a package that relies on diplib, but my automatic tests fail for Python 3.10 as it has problems getting and installing diplib. I'm pretty sure this is caused by the fact that there are no wheels built specifically for 3.10, meaning it has to compile diplib, which isn't working for some reason. Which is why I'm asking if it is maybe possible to upload some wheels built for Python 3.10, as that will allow me to extend the compatibility of my package.

Many thanks if this is possible.

**Comment by wcaarls** [comment]
I added Python 3.10 wheels to the deployment action. They should be uploaded when the next version is deployed (@crisluengo)

**Comment by crisluengo** [comment]
Thanks @wcaarls!

@tmtenbrink: We’ll prepare a new release within the next few weeks.

**Comment by crisluengo** [comment]
@tmtenbrink There are Python 3.10 wheels on PyPI now. Please let us know if you run into any issues!
