### ISSUE TITLE
Unrecognized function or variable 'numberofthreads'

### ISSUE THREAD

**Issue by boina** [DIPlib/diplib#97]
Hello,
I need to use the DIPlib library in Matlab. I have installed the DIPimage addon using the Matlab addon manager. This is part of another matlab addon that I would like to use (GUI_coloc).
When I run the readim comman I have this output:

```
>> readim
Unrecognized function or variable 'numberofthreads'.
Error in dippreferences (line 76)
      'NumberOfThreads',         struct('type','integer','value',numberofthreads),...
Error in dipgetpref (line 51)
      pref = dippreferences('get',name);
Error in readim (line 112)
   p = convertpath(dipgetpref('imagefilepath'));
```
I have looked and the function numberofthreads is present in the folder DIPimage/dipimage/private and the folder is in Matlab path.
I have also tried running the addon in the online version of Matlab to no avail, I get the same error so I imagine is not an OS issue.
I don't know how to get around this error. 

Any suggestion what to look for?

Thanks in advanced, jose.

OS: Linux Debian sid
Matlab: R2021b Update 1(9.11.0.1809720) 64bit
DIPimage: 3.0

**Comment by crisluengo** [comment]
The add-on manager just downloads the GitHub repository for you, it does not build the DIPlib library or the MEX-files, and it doesn't properly install the toolbox.

We have an [older version of the binaries for Windows](https://github.com/DIPlib/diplib/releases/tag/v3.0-beta.1) available for download. Please read the [installation instructions in the user manual](https://diplib.org/diplib-docs/sec_dum_installing.html#sec_dum_installing_windows).

Alternatively, build the toolbox from the sources you downloaded from GitHub, following [these instructions](https://github.com/DIPlib/diplib/blob/master/INSTALL_Windows.md) (assuming you're on windows, there are similar instruction files for other platforms in the root of the repository).

**Comment by crisluengo** [comment]
Sorry, just saw you are using Debian. We do not have any pre-build binaries for Linux distro's, but building yourself on Linux is quite simple. [Here are the Linux instructions](https://github.com/DIPlib/diplib/blob/master/INSTALL_Linux.md). Package names in the document are for Ubuntu, but should be similar on Debian. Would love if you could contribute Debian-specific information to those instructions!

**Comment by crisluengo** [comment]
A final alternative, given that the GUI_coloc tools seems to be quite old, is to use an older version of DiPimage. [Download DIPimage 2.9 here](https://diplib.org/download_2.9.html).

**Comment by boina** [comment]
Thank you very much @crisluengo. Tomorrow when I'm back to the lab I will try these two options and I will pay close attention to see if there are specific steps for a Debian install. I'll let you know how it goes.
