### ISSUE TITLE
Version number in source files

### ISSUE THREAD

**Issue by wcaarls** [DIPlib/diplib#98]
All source files state they are part of “DIPlib 3.0”, but we will be releasing 3.2.0 soon. Probably any mention of a specific version number should be removed.

**Comment by crisluengo** [comment]
Yeah, I noticed that too. When I wrote that line, I didn’t think of the implications…

removing the “3.0” from all files does imply touching all files, it’s an ugly commit. But it is probably the right thing to do.

I can probably convince my IDE to do a global search and replace?
