### ISSUE TITLE
Am I using FFTW in DIPimage?

### ISSUE THREAD

**Issue by ronligt** [DIPlib/diplib#99]
Is there a way to check in *DIPimage* (MATLAB) if FFTW is used or not?

**Comment by crisluengo** [comment]
Good point. I see we never updated the static `dip::libraryInformation` object (https://github.com/DIPlib/diplib/blob/master/src/library/information.cpp) when we added FFTW support (nor when we added freetype support). We’ll have to add this information. 

Typically I’d suggest to see if the DIPlib shared library depends on the FFTW shared library, but you’re doing static linking…

I guess currently the best way would be to compare the speed of the `ft` function for an image of an “easy size” and a prime size. The builtin FFT is fast for numbers that are a multiple of 2, 3 and 5. FFTW should be much faster than the builtin FFT for prime sizes. For example compare `ft` on a 256x256 image vs a 251x251 image (contents of the image doesn’t matter, try `newim(256,256)` for example).

**Comment by crisluengo** [comment]
By the way, for execution time use `timeit`:

    img1 = newim(256,256);
    img2 = newim(251,251);
    timeit(@()ft(img2)) / timeit(@()ft(img1))

The output value could be, for example, 10  for FFTW and 100 for the builtin FFT. We’d have to do a test to know what values exactly to expect in the two cases.

**Comment by crisluengo** [comment]
With the sizes above, you should see about 5 for the builtin FFT, and 1.3 for FFTW. I tried a larger size to get a more clear result:
```matlab
img1 = newim(1024,1024);
img2 = newim(1021,1021);
timeit(@()ft(img2)) / timeit(@()ft(img1))
```
Now I see 25 and 1.1.

**Comment by ronligt** [comment]
I've checked the times for *DIPimage* with and without FFTW

|   | 1024x1024 | 1021x1021|
|---|---|---|
|FFTW | 0.0138 | 0.0141|
|builtin | 0.0146 | 0.2257|

Looks very nice for FFTW!

**Comment by crisluengo** [comment]
Yes, indeed. The built-in FFT does any factors larger than 5 using the brute-force algorithm.

The built-in FFT is way faster than it was in DIPlib 2.9, but it's definitely not FFTW. :)
That's one of the reasons I added the `'fast'` option, it pads the image to a "nice" size that is a multiple of 2, 3 and 5.

**Comment by ronligt** [comment]
For me the issue is solved. @crisluengo however mentioned here a TODO item concerning `dip::libraryInformation`. I leave it up to him to close this issue if he seems fit.

**Comment by crisluengo** [comment]
`dip::libraryInformation` updated in c973b96a.
